//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5485 版自动生成。
// 
#pragma warning disable 1591

namespace HISCommonClient.WebReference1 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonServiceForHISSoap", Namespace="http://tempuri.org/")]
    public partial class CommonServiceForHIS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PushLisInpatientApplyByInpatientNoListOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushPatientEMPIInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CommonServiceForHIS() {
            this.Url = global::HISCommonClient.Properties.Settings.Default.HISCommonClient_WebReference1_CommonServiceForHIS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PushLisInpatientApplyByInpatientNoListCompletedEventHandler PushLisInpatientApplyByInpatientNoListCompleted;
        
        /// <remarks/>
        public event PushPatientEMPIInfoCompletedEventHandler PushPatientEMPIInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PushLisInpatientApplyByInpatientNoList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PushLisInpatientApplyByInpatientNoList(string[] inpatientNoList) {
            object[] results = this.Invoke("PushLisInpatientApplyByInpatientNoList", new object[] {
                        inpatientNoList});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PushLisInpatientApplyByInpatientNoListAsync(string[] inpatientNoList) {
            this.PushLisInpatientApplyByInpatientNoListAsync(inpatientNoList, null);
        }
        
        /// <remarks/>
        public void PushLisInpatientApplyByInpatientNoListAsync(string[] inpatientNoList, object userState) {
            if ((this.PushLisInpatientApplyByInpatientNoListOperationCompleted == null)) {
                this.PushLisInpatientApplyByInpatientNoListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushLisInpatientApplyByInpatientNoListOperationCompleted);
            }
            this.InvokeAsync("PushLisInpatientApplyByInpatientNoList", new object[] {
                        inpatientNoList}, this.PushLisInpatientApplyByInpatientNoListOperationCompleted, userState);
        }
        
        private void OnPushLisInpatientApplyByInpatientNoListOperationCompleted(object arg) {
            if ((this.PushLisInpatientApplyByInpatientNoListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushLisInpatientApplyByInpatientNoListCompleted(this, new PushLisInpatientApplyByInpatientNoListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PushPatientEMPIInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PushPatientEMPIInfo(string patientNo, string patientType) {
            object[] results = this.Invoke("PushPatientEMPIInfo", new object[] {
                        patientNo,
                        patientType});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PushPatientEMPIInfoAsync(string patientNo, string patientType) {
            this.PushPatientEMPIInfoAsync(patientNo, patientType, null);
        }
        
        /// <remarks/>
        public void PushPatientEMPIInfoAsync(string patientNo, string patientType, object userState) {
            if ((this.PushPatientEMPIInfoOperationCompleted == null)) {
                this.PushPatientEMPIInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushPatientEMPIInfoOperationCompleted);
            }
            this.InvokeAsync("PushPatientEMPIInfo", new object[] {
                        patientNo,
                        patientType}, this.PushPatientEMPIInfoOperationCompleted, userState);
        }
        
        private void OnPushPatientEMPIInfoOperationCompleted(object arg) {
            if ((this.PushPatientEMPIInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushPatientEMPIInfoCompleted(this, new PushPatientEMPIInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void PushLisInpatientApplyByInpatientNoListCompletedEventHandler(object sender, PushLisInpatientApplyByInpatientNoListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushLisInpatientApplyByInpatientNoListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushLisInpatientApplyByInpatientNoListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void PushPatientEMPIInfoCompletedEventHandler(object sender, PushPatientEMPIInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushPatientEMPIInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushPatientEMPIInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591