//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5485 版自动生成。
// 
#pragma warning disable 1591

namespace Nesoft.EMPI.HisPushServer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HISPushPatientInfoSoap11", Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")]
    public partial class HISPushPatientInfoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderValueField;
        
        private ResponseHeader responseHeaderValueField;
        
        private System.Threading.SendOrPostCallback HISPushPatientInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HISPushPatientInfoService() {
            this.Url = global::Nesoft.EMPI.Properties.Settings.Default.Nesoft_EMPI_HisPushServer_HISPushPatientInfoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderValue {
            get {
                return this.requestHeaderValueField;
            }
            set {
                this.requestHeaderValueField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderValue {
            get {
                return this.responseHeaderValueField;
            }
            set {
                this.responseHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HISPushPatientInfoCompletedEventHandler HISPushPatientInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("HISPushPatientInfoResponse", Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")]
        public HISPushPatientInfoResponse HISPushPatientInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")] HISPushPatientInfoRequest HISPushPatientInfoRequest) {
            object[] results = this.Invoke("HISPushPatientInfo", new object[] {
                        HISPushPatientInfoRequest});
            return ((HISPushPatientInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void HISPushPatientInfoAsync(HISPushPatientInfoRequest HISPushPatientInfoRequest) {
            this.HISPushPatientInfoAsync(HISPushPatientInfoRequest, null);
        }
        
        /// <remarks/>
        public void HISPushPatientInfoAsync(HISPushPatientInfoRequest HISPushPatientInfoRequest, object userState) {
            if ((this.HISPushPatientInfoOperationCompleted == null)) {
                this.HISPushPatientInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHISPushPatientInfoOperationCompleted);
            }
            this.InvokeAsync("HISPushPatientInfo", new object[] {
                        HISPushPatientInfoRequest}, this.HISPushPatientInfoOperationCompleted, userState);
        }
        
        private void OnHISPushPatientInfoOperationCompleted(object arg) {
            if ((this.HISPushPatientInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HISPushPatientInfoCompleted(this, new HISPushPatientInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/", IsNullable=false)]
    public partial class ResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        private string internalTokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string InternalToken {
            get {
                return this.internalTokenField;
            }
            set {
                this.internalTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/", IsNullable=false)]
    public partial class RequestHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        private string systemCodeField;
        
        private string channelMarkField;
        
        private string converterMarkField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string SystemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelMark {
            get {
                return this.channelMarkField;
            }
            set {
                this.channelMarkField = value;
            }
        }
        
        /// <remarks/>
        public string ConverterMark {
            get {
                return this.converterMarkField;
            }
            set {
                this.converterMarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")]
    public partial class HISPushPatientInfoRequest {
        
        private HISPushPatientInfoRequestMessage messageField;
        
        /// <remarks/>
        public HISPushPatientInfoRequestMessage message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")]
    public partial class HISPushPatientInfoRequestMessage {
        
        private string nAMEField;
        
        private string iDNOField;
        
        private string sEXField;
        
        private string bIRTHDAYField;
        
        private string cNYField;
        
        private string cNYNAMEField;
        
        private string aCTField;
        
        private string aDDRField;
        
        private string zPCODEField;
        
        private string aBOBLDField;
        
        private string rHBLDField;
        
        private string nTNField;
        
        private string bCPField;
        
        private string cTORField;
        
        private string cTORTELField;
        
        private string cTORLTNField;
        
        private string hMTELField;
        
        private string mOBILEField;
        
        private string eMLField;
        
        private string cPYField;
        
        private string cPYTELField;
        
        private string mRGField;
        
        private string pFSNField;
        
        private string mEMOField;
        
        private string cARDNOField;
        
        private string cARDTYPEField;
        
        private string pATIENTTYPEField;
        
        private string eMPINOField;
        
        private string oPERCODEField;
        
        private string oPERNAMEField;
        
        private string dEVOTEField;
        
        private string nOTE1Field;
        
        private string nOTE2Field;
        
        private string nOTE3Field;
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string IDNO {
            get {
                return this.iDNOField;
            }
            set {
                this.iDNOField = value;
            }
        }
        
        /// <remarks/>
        public string SEX {
            get {
                return this.sEXField;
            }
            set {
                this.sEXField = value;
            }
        }
        
        /// <remarks/>
        public string BIRTHDAY {
            get {
                return this.bIRTHDAYField;
            }
            set {
                this.bIRTHDAYField = value;
            }
        }
        
        /// <remarks/>
        public string CNY {
            get {
                return this.cNYField;
            }
            set {
                this.cNYField = value;
            }
        }
        
        /// <remarks/>
        public string CNYNAME {
            get {
                return this.cNYNAMEField;
            }
            set {
                this.cNYNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ACT {
            get {
                return this.aCTField;
            }
            set {
                this.aCTField = value;
            }
        }
        
        /// <remarks/>
        public string ADDR {
            get {
                return this.aDDRField;
            }
            set {
                this.aDDRField = value;
            }
        }
        
        /// <remarks/>
        public string ZPCODE {
            get {
                return this.zPCODEField;
            }
            set {
                this.zPCODEField = value;
            }
        }
        
        /// <remarks/>
        public string ABOBLD {
            get {
                return this.aBOBLDField;
            }
            set {
                this.aBOBLDField = value;
            }
        }
        
        /// <remarks/>
        public string RHBLD {
            get {
                return this.rHBLDField;
            }
            set {
                this.rHBLDField = value;
            }
        }
        
        /// <remarks/>
        public string NTN {
            get {
                return this.nTNField;
            }
            set {
                this.nTNField = value;
            }
        }
        
        /// <remarks/>
        public string BCP {
            get {
                return this.bCPField;
            }
            set {
                this.bCPField = value;
            }
        }
        
        /// <remarks/>
        public string CTOR {
            get {
                return this.cTORField;
            }
            set {
                this.cTORField = value;
            }
        }
        
        /// <remarks/>
        public string CTORTEL {
            get {
                return this.cTORTELField;
            }
            set {
                this.cTORTELField = value;
            }
        }
        
        /// <remarks/>
        public string CTORLTN {
            get {
                return this.cTORLTNField;
            }
            set {
                this.cTORLTNField = value;
            }
        }
        
        /// <remarks/>
        public string HMTEL {
            get {
                return this.hMTELField;
            }
            set {
                this.hMTELField = value;
            }
        }
        
        /// <remarks/>
        public string MOBILE {
            get {
                return this.mOBILEField;
            }
            set {
                this.mOBILEField = value;
            }
        }
        
        /// <remarks/>
        public string EML {
            get {
                return this.eMLField;
            }
            set {
                this.eMLField = value;
            }
        }
        
        /// <remarks/>
        public string CPY {
            get {
                return this.cPYField;
            }
            set {
                this.cPYField = value;
            }
        }
        
        /// <remarks/>
        public string CPYTEL {
            get {
                return this.cPYTELField;
            }
            set {
                this.cPYTELField = value;
            }
        }
        
        /// <remarks/>
        public string MRG {
            get {
                return this.mRGField;
            }
            set {
                this.mRGField = value;
            }
        }
        
        /// <remarks/>
        public string PFSN {
            get {
                return this.pFSNField;
            }
            set {
                this.pFSNField = value;
            }
        }
        
        /// <remarks/>
        public string MEMO {
            get {
                return this.mEMOField;
            }
            set {
                this.mEMOField = value;
            }
        }
        
        /// <remarks/>
        public string CARDNO {
            get {
                return this.cARDNOField;
            }
            set {
                this.cARDNOField = value;
            }
        }
        
        /// <remarks/>
        public string CARDTYPE {
            get {
                return this.cARDTYPEField;
            }
            set {
                this.cARDTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string PATIENTTYPE {
            get {
                return this.pATIENTTYPEField;
            }
            set {
                this.pATIENTTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string EMPINO {
            get {
                return this.eMPINOField;
            }
            set {
                this.eMPINOField = value;
            }
        }
        
        /// <remarks/>
        public string OPERCODE {
            get {
                return this.oPERCODEField;
            }
            set {
                this.oPERCODEField = value;
            }
        }
        
        /// <remarks/>
        public string OPERNAME {
            get {
                return this.oPERNAMEField;
            }
            set {
                this.oPERNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DEVOTE {
            get {
                return this.dEVOTEField;
            }
            set {
                this.dEVOTEField = value;
            }
        }
        
        /// <remarks/>
        public string NOTE1 {
            get {
                return this.nOTE1Field;
            }
            set {
                this.nOTE1Field = value;
            }
        }
        
        /// <remarks/>
        public string NOTE2 {
            get {
                return this.nOTE2Field;
            }
            set {
                this.nOTE2Field = value;
            }
        }
        
        /// <remarks/>
        public string NOTE3 {
            get {
                return this.nOTE3Field;
            }
            set {
                this.nOTE3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/HISPushPatientInfo/")]
    public partial class HISPushPatientInfoResponse {
        
        private string hISPushPatientInfoResultField;
        
        /// <remarks/>
        public string HISPushPatientInfoResult {
            get {
                return this.hISPushPatientInfoResultField;
            }
            set {
                this.hISPushPatientInfoResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void HISPushPatientInfoCompletedEventHandler(object sender, HISPushPatientInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HISPushPatientInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HISPushPatientInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HISPushPatientInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HISPushPatientInfoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591