//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.SOC.Local.OutpatientFee.ZhuHai.PushMsgService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PushMsgService.IPushMsginterface")]
    public interface IPushMsginterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushMsginterface/PushMsg", ReplyAction="http://tempuri.org/IPushMsginterface/PushMsgResponse")]
        string PushMsg(int HospitalId, int Source, int Type, string Content, string Data, string Sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushMsginterface/QrCodeFee", ReplyAction="http://tempuri.org/IPushMsginterface/QrCodeFeeResponse")]
        string QrCodeFee(string PayType, string clinicCode, string[] recipes, double totalAmount, string authCode, string outTradeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushMsginterface/QueryOrder", ReplyAction="http://tempuri.org/IPushMsginterface/QueryOrderResponse")]
        string QueryOrder(string OutTradeNo, string TradeNo, string ClinicCode, string PayType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushMsginterface/CancelQrCodeFee", ReplyAction="http://tempuri.org/IPushMsginterface/CancelQrCodeFeeResponse")]
        string CancelQrCodeFee(string OutTradeNo, string TradeNo, double TotalAmount, string PayType, string ClinicCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPushMsginterfaceChannel : Neusoft.SOC.Local.OutpatientFee.ZhuHai.PushMsgService.IPushMsginterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PushMsginterfaceClient : System.ServiceModel.ClientBase<Neusoft.SOC.Local.OutpatientFee.ZhuHai.PushMsgService.IPushMsginterface>, Neusoft.SOC.Local.OutpatientFee.ZhuHai.PushMsgService.IPushMsginterface {
        
        public PushMsginterfaceClient() {
        }
        
        public PushMsginterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushMsginterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushMsginterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushMsginterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PushMsg(int HospitalId, int Source, int Type, string Content, string Data, string Sid) {
            return base.Channel.PushMsg(HospitalId, Source, Type, Content, Data, Sid);
        }
        
        public string QrCodeFee(string PayType, string clinicCode, string[] recipes, double totalAmount, string authCode, string outTradeNo) {
            return base.Channel.QrCodeFee(PayType, clinicCode, recipes, totalAmount, authCode, outTradeNo);
        }
        
        public string QueryOrder(string OutTradeNo, string TradeNo, string ClinicCode, string PayType) {
            return base.Channel.QueryOrder(OutTradeNo, TradeNo, ClinicCode, PayType);
        }
        
        public string CancelQrCodeFee(string OutTradeNo, string TradeNo, double TotalAmount, string PayType, string ClinicCode) {
            return base.Channel.CancelQrCodeFee(OutTradeNo, TradeNo, TotalAmount, PayType, ClinicCode);
        }
    }
}
