//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9148
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.9148 版自动生成。
// 
#pragma warning disable 1591

namespace Neusoft.SOC.Local.OutpatientFee.ZhuHai.GHpayService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetpayOperationCompleted;
        
        private System.Threading.SendOrPostCallback PayStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRefundOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnstatOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Neusoft.SOC.Local.OutpatientFee.ZhuHai.Properties.Settings.Default.SOC_Local_OutpatientFee_ZhuHai_GHpayService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetpayCompletedEventHandler GetpayCompleted;
        
        /// <remarks/>
        public event PayStatusCompletedEventHandler PayStatusCompleted;
        
        /// <remarks/>
        public event GetRefundCompletedEventHandler GetRefundCompleted;
        
        /// <remarks/>
        public event ReturnstatCompletedEventHandler ReturnstatCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Getpay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Getpay(string setQrCode, string setOutTradeNo, string setOrderAmt) {
            object[] results = this.Invoke("Getpay", new object[] {
                        setQrCode,
                        setOutTradeNo,
                        setOrderAmt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetpayAsync(string setQrCode, string setOutTradeNo, string setOrderAmt) {
            this.GetpayAsync(setQrCode, setOutTradeNo, setOrderAmt, null);
        }
        
        /// <remarks/>
        public void GetpayAsync(string setQrCode, string setOutTradeNo, string setOrderAmt, object userState) {
            if ((this.GetpayOperationCompleted == null)) {
                this.GetpayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetpayOperationCompleted);
            }
            this.InvokeAsync("Getpay", new object[] {
                        setQrCode,
                        setOutTradeNo,
                        setOrderAmt}, this.GetpayOperationCompleted, userState);
        }
        
        private void OnGetpayOperationCompleted(object arg) {
            if ((this.GetpayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetpayCompleted(this, new GetpayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PayStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PayStatus(string setOutTradeNo) {
            object[] results = this.Invoke("PayStatus", new object[] {
                        setOutTradeNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PayStatusAsync(string setOutTradeNo) {
            this.PayStatusAsync(setOutTradeNo, null);
        }
        
        /// <remarks/>
        public void PayStatusAsync(string setOutTradeNo, object userState) {
            if ((this.PayStatusOperationCompleted == null)) {
                this.PayStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPayStatusOperationCompleted);
            }
            this.InvokeAsync("PayStatus", new object[] {
                        setOutTradeNo}, this.PayStatusOperationCompleted, userState);
        }
        
        private void OnPayStatusOperationCompleted(object arg) {
            if ((this.PayStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PayStatusCompleted(this, new PayStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRefund", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRefund(string setOutTradeNo, string setRejectNo, string setRejectAmt, string setOperId) {
            object[] results = this.Invoke("GetRefund", new object[] {
                        setOutTradeNo,
                        setRejectNo,
                        setRejectAmt,
                        setOperId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRefundAsync(string setOutTradeNo, string setRejectNo, string setRejectAmt, string setOperId) {
            this.GetRefundAsync(setOutTradeNo, setRejectNo, setRejectAmt, setOperId, null);
        }
        
        /// <remarks/>
        public void GetRefundAsync(string setOutTradeNo, string setRejectNo, string setRejectAmt, string setOperId, object userState) {
            if ((this.GetRefundOperationCompleted == null)) {
                this.GetRefundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRefundOperationCompleted);
            }
            this.InvokeAsync("GetRefund", new object[] {
                        setOutTradeNo,
                        setRejectNo,
                        setRejectAmt,
                        setOperId}, this.GetRefundOperationCompleted, userState);
        }
        
        private void OnGetRefundOperationCompleted(object arg) {
            if ((this.GetRefundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRefundCompleted(this, new GetRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Returnstat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Returnstat(string setOutTradeNo, string setRejectNo) {
            object[] results = this.Invoke("Returnstat", new object[] {
                        setOutTradeNo,
                        setRejectNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnstatAsync(string setOutTradeNo, string setRejectNo) {
            this.ReturnstatAsync(setOutTradeNo, setRejectNo, null);
        }
        
        /// <remarks/>
        public void ReturnstatAsync(string setOutTradeNo, string setRejectNo, object userState) {
            if ((this.ReturnstatOperationCompleted == null)) {
                this.ReturnstatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnstatOperationCompleted);
            }
            this.InvokeAsync("Returnstat", new object[] {
                        setOutTradeNo,
                        setRejectNo}, this.ReturnstatOperationCompleted, userState);
        }
        
        private void OnReturnstatOperationCompleted(object arg) {
            if ((this.ReturnstatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnstatCompleted(this, new ReturnstatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void GetpayCompletedEventHandler(object sender, GetpayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetpayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetpayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void PayStatusCompletedEventHandler(object sender, PayStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PayStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void GetRefundCompletedEventHandler(object sender, GetRefundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRefundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRefundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void ReturnstatCompletedEventHandler(object sender, ReturnstatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnstatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnstatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591