//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5485 版自动生成。
// 
#pragma warning disable 1591

namespace LisService.LisServiceReference1 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PushInpLabApplySoap11", Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    public partial class PushInpLabApplyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderValueField;
        
        private ResponseHeader responseHeaderValueField;
        
        private System.Threading.SendOrPostCallback PushInpLabApplyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PushInpLabApplyService() {
            this.Url = global::LisService.Properties.Settings.Default.LisService_LisServiceReference1_PushInpLabApplyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderValue {
            get {
                return this.requestHeaderValueField;
            }
            set {
                this.requestHeaderValueField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderValue {
            get {
                return this.responseHeaderValueField;
            }
            set {
                this.responseHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PushInpLabApplyCompletedEventHandler PushInpLabApplyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PushInpLabApplyResponse", Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
        public PushInpLabApplyResponse PushInpLabApply([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")] PushInpLabApplyRequest PushInpLabApplyRequest) {
            object[] results = this.Invoke("PushInpLabApply", new object[] {
                        PushInpLabApplyRequest});
            return ((PushInpLabApplyResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PushInpLabApplyAsync(PushInpLabApplyRequest PushInpLabApplyRequest) {
            this.PushInpLabApplyAsync(PushInpLabApplyRequest, null);
        }
        
        /// <remarks/>
        public void PushInpLabApplyAsync(PushInpLabApplyRequest PushInpLabApplyRequest, object userState) {
            if ((this.PushInpLabApplyOperationCompleted == null)) {
                this.PushInpLabApplyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushInpLabApplyOperationCompleted);
            }
            this.InvokeAsync("PushInpLabApply", new object[] {
                        PushInpLabApplyRequest}, this.PushInpLabApplyOperationCompleted, userState);
        }
        
        private void OnPushInpLabApplyOperationCompleted(object arg) {
            if ((this.PushInpLabApplyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushInpLabApplyCompleted(this, new PushInpLabApplyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.neusoft.com/hsb/PushInpLabApply/", IsNullable=false)]
    public partial class ResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        private string internalTokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string InternalToken {
            get {
                return this.internalTokenField;
            }
            set {
                this.internalTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.neusoft.com/hsb/PushInpLabApply/", IsNullable=false)]
    public partial class RequestHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string tokenField;
        
        private string systemCodeField;
        
        private string channelMarkField;
        
        private string converterMarkField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string SystemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelMark {
            get {
                return this.channelMarkField;
            }
            set {
                this.channelMarkField = value;
            }
        }
        
        /// <remarks/>
        public string ConverterMark {
            get {
                return this.converterMarkField;
            }
            set {
                this.converterMarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    public partial class PushInpLabApplyRequest {
        
        private PushInpLabApplyRequestMessage messageField;
        
        /// <remarks/>
        public PushInpLabApplyRequestMessage message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    public partial class PushInpLabApplyRequestMessage {
        
        private PushInpLabApplyRequestMessageLISApply lISApplyField;
        
        /// <remarks/>
        public PushInpLabApplyRequestMessageLISApply LISApply {
            get {
                return this.lISApplyField;
            }
            set {
                this.lISApplyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    public partial class PushInpLabApplyRequestMessageLISApply {
        
        private PushInpLabApplyRequestMessageLISApplyPATIENTINFO pATIENTINFOField;
        
        private PushInpLabApplyRequestMessageLISApplyAPPLYINFO[] aPPLYINFOField;
        
        /// <remarks/>
        public PushInpLabApplyRequestMessageLISApplyPATIENTINFO PATIENTINFO {
            get {
                return this.pATIENTINFOField;
            }
            set {
                this.pATIENTINFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("APPLYINFO")]
        public PushInpLabApplyRequestMessageLISApplyAPPLYINFO[] APPLYINFO {
            get {
                return this.aPPLYINFOField;
            }
            set {
                this.aPPLYINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    public partial class PushInpLabApplyRequestMessageLISApplyPATIENTINFO {
        
        private string pTNT_IDField;
        
        private string vISIT_IDField;
        
        private string eMPIField;
        
        private string iD_CARDField;
        
        private string iC_CARDField;
        
        private string cTAT_ADDRField;
        
        private string pHONE_NUMField;
        
        private string pTNT_NOField;
        
        private string pTNT_NO_TYPEField;
        
        private string pTNT_NAMEField;
        
        private string pTNT_SEXField;
        
        private string pTNT_AGEField;
        
        private string pTNT_AGE_UNITField;
        
        private string aDMISSE_DATEField;
        
        private string pTNT_BIRTHField;
        
        private string pTNT_BED_NOField;
        
        private string dIAG_INFOField;
        
        /// <remarks/>
        public string PTNT_ID {
            get {
                return this.pTNT_IDField;
            }
            set {
                this.pTNT_IDField = value;
            }
        }
        
        /// <remarks/>
        public string VISIT_ID {
            get {
                return this.vISIT_IDField;
            }
            set {
                this.vISIT_IDField = value;
            }
        }
        
        /// <remarks/>
        public string EMPI {
            get {
                return this.eMPIField;
            }
            set {
                this.eMPIField = value;
            }
        }
        
        /// <remarks/>
        public string ID_CARD {
            get {
                return this.iD_CARDField;
            }
            set {
                this.iD_CARDField = value;
            }
        }
        
        /// <remarks/>
        public string IC_CARD {
            get {
                return this.iC_CARDField;
            }
            set {
                this.iC_CARDField = value;
            }
        }
        
        /// <remarks/>
        public string CTAT_ADDR {
            get {
                return this.cTAT_ADDRField;
            }
            set {
                this.cTAT_ADDRField = value;
            }
        }
        
        /// <remarks/>
        public string PHONE_NUM {
            get {
                return this.pHONE_NUMField;
            }
            set {
                this.pHONE_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_NO {
            get {
                return this.pTNT_NOField;
            }
            set {
                this.pTNT_NOField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_NO_TYPE {
            get {
                return this.pTNT_NO_TYPEField;
            }
            set {
                this.pTNT_NO_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_NAME {
            get {
                return this.pTNT_NAMEField;
            }
            set {
                this.pTNT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_SEX {
            get {
                return this.pTNT_SEXField;
            }
            set {
                this.pTNT_SEXField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_AGE {
            get {
                return this.pTNT_AGEField;
            }
            set {
                this.pTNT_AGEField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_AGE_UNIT {
            get {
                return this.pTNT_AGE_UNITField;
            }
            set {
                this.pTNT_AGE_UNITField = value;
            }
        }
        
        /// <remarks/>
        public string ADMISSE_DATE {
            get {
                return this.aDMISSE_DATEField;
            }
            set {
                this.aDMISSE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_BIRTH {
            get {
                return this.pTNT_BIRTHField;
            }
            set {
                this.pTNT_BIRTHField = value;
            }
        }
        
        /// <remarks/>
        public string PTNT_BED_NO {
            get {
                return this.pTNT_BED_NOField;
            }
            set {
                this.pTNT_BED_NOField = value;
            }
        }
        
        /// <remarks/>
        public string DIAG_INFO {
            get {
                return this.dIAG_INFOField;
            }
            set {
                this.dIAG_INFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    public partial class PushInpLabApplyRequestMessageLISApplyAPPLYINFO {
        
        private string aPLY_IDField;
        
        private string aPLY_SRCField;
        
        private string aPLY_FLOW_NUMField;
        
        private string aPLY_CREATE_DATEField;
        
        private string eMCY_MRKField;
        
        private string aPLY_DATEField;
        
        private string dEPT_KEYField;
        
        private string dEPT_NAMEField;
        
        private string dOC_KEYField;
        
        private string dOC_NAMEField;
        
        private string aPLY_ITM_KEYField;
        
        private string aPLY_ITM_NAMEField;
        
        private string sMPL_KEYField;
        
        private string sMPL_NAMEField;
        
        private string bODY_PARTField;
        
        private string rEMARKField;
        
        private string eXEC_STATUSField;
        
        /// <remarks/>
        public string APLY_ID {
            get {
                return this.aPLY_IDField;
            }
            set {
                this.aPLY_IDField = value;
            }
        }
        
        /// <remarks/>
        public string APLY_SRC {
            get {
                return this.aPLY_SRCField;
            }
            set {
                this.aPLY_SRCField = value;
            }
        }
        
        /// <remarks/>
        public string APLY_FLOW_NUM {
            get {
                return this.aPLY_FLOW_NUMField;
            }
            set {
                this.aPLY_FLOW_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string APLY_CREATE_DATE {
            get {
                return this.aPLY_CREATE_DATEField;
            }
            set {
                this.aPLY_CREATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string EMCY_MRK {
            get {
                return this.eMCY_MRKField;
            }
            set {
                this.eMCY_MRKField = value;
            }
        }
        
        /// <remarks/>
        public string APLY_DATE {
            get {
                return this.aPLY_DATEField;
            }
            set {
                this.aPLY_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string DEPT_KEY {
            get {
                return this.dEPT_KEYField;
            }
            set {
                this.dEPT_KEYField = value;
            }
        }
        
        /// <remarks/>
        public string DEPT_NAME {
            get {
                return this.dEPT_NAMEField;
            }
            set {
                this.dEPT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DOC_KEY {
            get {
                return this.dOC_KEYField;
            }
            set {
                this.dOC_KEYField = value;
            }
        }
        
        /// <remarks/>
        public string DOC_NAME {
            get {
                return this.dOC_NAMEField;
            }
            set {
                this.dOC_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string APLY_ITM_KEY {
            get {
                return this.aPLY_ITM_KEYField;
            }
            set {
                this.aPLY_ITM_KEYField = value;
            }
        }
        
        /// <remarks/>
        public string APLY_ITM_NAME {
            get {
                return this.aPLY_ITM_NAMEField;
            }
            set {
                this.aPLY_ITM_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SMPL_KEY {
            get {
                return this.sMPL_KEYField;
            }
            set {
                this.sMPL_KEYField = value;
            }
        }
        
        /// <remarks/>
        public string SMPL_NAME {
            get {
                return this.sMPL_NAMEField;
            }
            set {
                this.sMPL_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string BODY_PART {
            get {
                return this.bODY_PARTField;
            }
            set {
                this.bODY_PARTField = value;
            }
        }
        
        /// <remarks/>
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
            }
        }
        
        /// <remarks/>
        public string EXEC_STATUS {
            get {
                return this.eXEC_STATUSField;
            }
            set {
                this.eXEC_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.neusoft.com/hsb/PushInpLabApply/")]
    public partial class PushInpLabApplyResponse {
        
        private string returnField;
        
        /// <remarks/>
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void PushInpLabApplyCompletedEventHandler(object sender, PushInpLabApplyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushInpLabApplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushInpLabApplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PushInpLabApplyResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PushInpLabApplyResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591