//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5472 版自动生成。
// 
#pragma warning disable 1591

namespace Nesoft.EMPI.EMPIWebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EMPIBinding", Namespace="http://cdr.empi.neusoft.com/")]
    public partial class EMPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPatientInfoByEmpiOperationCompleted;
        
        private System.Threading.SendOrPostCallback regEmpiOperationCompleted;
        
        private System.Threading.SendOrPostCallback delPatientInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPatientInfoByLocalIndexOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIndexByLocalIndexOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EMPI() {
            this.Url = global::Nesoft.EMPI.Properties.Settings.Default.Nesoft_EMPI_EMPIWebReference_EMPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPatientInfoByEmpiCompletedEventHandler getPatientInfoByEmpiCompleted;
        
        /// <remarks/>
        public event regEmpiCompletedEventHandler regEmpiCompleted;
        
        /// <remarks/>
        public event delPatientInfoCompletedEventHandler delPatientInfoCompleted;
        
        /// <remarks/>
        public event getPatientInfoByLocalIndexCompletedEventHandler getPatientInfoByLocalIndexCompleted;
        
        /// <remarks/>
        public event getIndexByLocalIndexCompletedEventHandler getIndexByLocalIndexCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cdr.empi.neusoft.com/", ResponseNamespace="http://cdr.empi.neusoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getPatientInfoByEmpi(string empi) {
            object[] results = this.Invoke("getPatientInfoByEmpi", new object[] {
                        empi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPatientInfoByEmpiAsync(string empi) {
            this.getPatientInfoByEmpiAsync(empi, null);
        }
        
        /// <remarks/>
        public void getPatientInfoByEmpiAsync(string empi, object userState) {
            if ((this.getPatientInfoByEmpiOperationCompleted == null)) {
                this.getPatientInfoByEmpiOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPatientInfoByEmpiOperationCompleted);
            }
            this.InvokeAsync("getPatientInfoByEmpi", new object[] {
                        empi}, this.getPatientInfoByEmpiOperationCompleted, userState);
        }
        
        private void OngetPatientInfoByEmpiOperationCompleted(object arg) {
            if ((this.getPatientInfoByEmpiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPatientInfoByEmpiCompleted(this, new getPatientInfoByEmpiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cdr.empi.neusoft.com/", ResponseNamespace="http://cdr.empi.neusoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string regEmpi(string patientInfo) {
            object[] results = this.Invoke("regEmpi", new object[] {
                        patientInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void regEmpiAsync(string patientInfo) {
            this.regEmpiAsync(patientInfo, null);
        }
        
        /// <remarks/>
        public void regEmpiAsync(string patientInfo, object userState) {
            if ((this.regEmpiOperationCompleted == null)) {
                this.regEmpiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregEmpiOperationCompleted);
            }
            this.InvokeAsync("regEmpi", new object[] {
                        patientInfo}, this.regEmpiOperationCompleted, userState);
        }
        
        private void OnregEmpiOperationCompleted(object arg) {
            if ((this.regEmpiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.regEmpiCompleted(this, new regEmpiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cdr.empi.neusoft.com/", ResponseNamespace="http://cdr.empi.neusoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string delPatientInfo(string patientInfo) {
            object[] results = this.Invoke("delPatientInfo", new object[] {
                        patientInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delPatientInfoAsync(string patientInfo) {
            this.delPatientInfoAsync(patientInfo, null);
        }
        
        /// <remarks/>
        public void delPatientInfoAsync(string patientInfo, object userState) {
            if ((this.delPatientInfoOperationCompleted == null)) {
                this.delPatientInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelPatientInfoOperationCompleted);
            }
            this.InvokeAsync("delPatientInfo", new object[] {
                        patientInfo}, this.delPatientInfoOperationCompleted, userState);
        }
        
        private void OndelPatientInfoOperationCompleted(object arg) {
            if ((this.delPatientInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delPatientInfoCompleted(this, new delPatientInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cdr.empi.neusoft.com/", ResponseNamespace="http://cdr.empi.neusoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getPatientInfoByLocalIndex(string localindex) {
            object[] results = this.Invoke("getPatientInfoByLocalIndex", new object[] {
                        localindex});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPatientInfoByLocalIndexAsync(string localindex) {
            this.getPatientInfoByLocalIndexAsync(localindex, null);
        }
        
        /// <remarks/>
        public void getPatientInfoByLocalIndexAsync(string localindex, object userState) {
            if ((this.getPatientInfoByLocalIndexOperationCompleted == null)) {
                this.getPatientInfoByLocalIndexOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPatientInfoByLocalIndexOperationCompleted);
            }
            this.InvokeAsync("getPatientInfoByLocalIndex", new object[] {
                        localindex}, this.getPatientInfoByLocalIndexOperationCompleted, userState);
        }
        
        private void OngetPatientInfoByLocalIndexOperationCompleted(object arg) {
            if ((this.getPatientInfoByLocalIndexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPatientInfoByLocalIndexCompleted(this, new getPatientInfoByLocalIndexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cdr.empi.neusoft.com/", ResponseNamespace="http://cdr.empi.neusoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getIndexByLocalIndex(string localindex) {
            object[] results = this.Invoke("getIndexByLocalIndex", new object[] {
                        localindex});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getIndexByLocalIndexAsync(string localindex) {
            this.getIndexByLocalIndexAsync(localindex, null);
        }
        
        /// <remarks/>
        public void getIndexByLocalIndexAsync(string localindex, object userState) {
            if ((this.getIndexByLocalIndexOperationCompleted == null)) {
                this.getIndexByLocalIndexOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIndexByLocalIndexOperationCompleted);
            }
            this.InvokeAsync("getIndexByLocalIndex", new object[] {
                        localindex}, this.getIndexByLocalIndexOperationCompleted, userState);
        }
        
        private void OngetIndexByLocalIndexOperationCompleted(object arg) {
            if ((this.getIndexByLocalIndexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIndexByLocalIndexCompleted(this, new getIndexByLocalIndexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getPatientInfoByEmpiCompletedEventHandler(object sender, getPatientInfoByEmpiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPatientInfoByEmpiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPatientInfoByEmpiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void regEmpiCompletedEventHandler(object sender, regEmpiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class regEmpiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal regEmpiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void delPatientInfoCompletedEventHandler(object sender, delPatientInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delPatientInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delPatientInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getPatientInfoByLocalIndexCompletedEventHandler(object sender, getPatientInfoByLocalIndexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPatientInfoByLocalIndexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPatientInfoByLocalIndexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getIndexByLocalIndexCompletedEventHandler(object sender, getIndexByLocalIndexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIndexByLocalIndexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIndexByLocalIndexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591