//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5485 版自动生成。
// 
#pragma warning disable 1591

namespace HISCommonClient.SOAPMsgSer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MessageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageToDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasUnreadMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveReadedMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveSendedMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveAllMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllMessageByDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMessageReadedOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDoctorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDoctorListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptDoctorListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageService() {
            this.Url = global::HISCommonClient.Properties.Settings.Default.HISCommonClient_SOAPMsgSer_MessageService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event SendMessageToDeptCompletedEventHandler SendMessageToDeptCompleted;
        
        /// <remarks/>
        public event ReceiveMessageCompletedEventHandler ReceiveMessageCompleted;
        
        /// <remarks/>
        public event HasUnreadMessageCompletedEventHandler HasUnreadMessageCompleted;
        
        /// <remarks/>
        public event ReceiveReadedMessageCompletedEventHandler ReceiveReadedMessageCompleted;
        
        /// <remarks/>
        public event ReceiveSendedMessageCompletedEventHandler ReceiveSendedMessageCompleted;
        
        /// <remarks/>
        public event ReceiveAllMessageCompletedEventHandler ReceiveAllMessageCompleted;
        
        /// <remarks/>
        public event GetAllMessageByDeptCompletedEventHandler GetAllMessageByDeptCompleted;
        
        /// <remarks/>
        public event SetMessageReadedCompletedEventHandler SetMessageReadedCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GetDoctorCompletedEventHandler GetDoctorCompleted;
        
        /// <remarks/>
        public event GetDoctorListCompletedEventHandler GetDoctorListCompleted;
        
        /// <remarks/>
        public event GetDeptDoctorListCompletedEventHandler GetDeptDoctorListCompleted;
        
        /// <remarks/>
        public event RegisterUserCompletedEventHandler RegisterUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMessage(string userid, string deptcode, string tos, string deptcodes, string title, string message, string msgtype, string fixedTime, bool sendToMobile, string businessmessageid, string businessmessagecontent) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        userid,
                        deptcode,
                        tos,
                        deptcodes,
                        title,
                        message,
                        msgtype,
                        fixedTime,
                        sendToMobile,
                        businessmessageid,
                        businessmessagecontent});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(string userid, string deptcode, string tos, string deptcodes, string title, string message, string msgtype, string fixedTime, bool sendToMobile, string businessmessageid, string businessmessagecontent) {
            this.SendMessageAsync(userid, deptcode, tos, deptcodes, title, message, msgtype, fixedTime, sendToMobile, businessmessageid, businessmessagecontent, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(string userid, string deptcode, string tos, string deptcodes, string title, string message, string msgtype, string fixedTime, bool sendToMobile, string businessmessageid, string businessmessagecontent, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        userid,
                        deptcode,
                        tos,
                        deptcodes,
                        title,
                        message,
                        msgtype,
                        fixedTime,
                        sendToMobile,
                        businessmessageid,
                        businessmessagecontent}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessageToDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMessageToDept(string userid, string deptcode, string dept, string title, string message, string msgtype, string fixedTime, bool sendToMobile, string businessmessageid, string businessmessagecontent) {
            object[] results = this.Invoke("SendMessageToDept", new object[] {
                        userid,
                        deptcode,
                        dept,
                        title,
                        message,
                        msgtype,
                        fixedTime,
                        sendToMobile,
                        businessmessageid,
                        businessmessagecontent});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageToDeptAsync(string userid, string deptcode, string dept, string title, string message, string msgtype, string fixedTime, bool sendToMobile, string businessmessageid, string businessmessagecontent) {
            this.SendMessageToDeptAsync(userid, deptcode, dept, title, message, msgtype, fixedTime, sendToMobile, businessmessageid, businessmessagecontent, null);
        }
        
        /// <remarks/>
        public void SendMessageToDeptAsync(string userid, string deptcode, string dept, string title, string message, string msgtype, string fixedTime, bool sendToMobile, string businessmessageid, string businessmessagecontent, object userState) {
            if ((this.SendMessageToDeptOperationCompleted == null)) {
                this.SendMessageToDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageToDeptOperationCompleted);
            }
            this.InvokeAsync("SendMessageToDept", new object[] {
                        userid,
                        deptcode,
                        dept,
                        title,
                        message,
                        msgtype,
                        fixedTime,
                        sendToMobile,
                        businessmessageid,
                        businessmessagecontent}, this.SendMessageToDeptOperationCompleted, userState);
        }
        
        private void OnSendMessageToDeptOperationCompleted(object arg) {
            if ((this.SendMessageToDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageToDeptCompleted(this, new SendMessageToDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgInfo[] ReceiveMessage(string userid, string deptcode) {
            object[] results = this.Invoke("ReceiveMessage", new object[] {
                        userid,
                        deptcode});
            return ((MsgInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(string userid, string deptcode) {
            this.ReceiveMessageAsync(userid, deptcode, null);
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(string userid, string deptcode, object userState) {
            if ((this.ReceiveMessageOperationCompleted == null)) {
                this.ReceiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveMessage", new object[] {
                        userid,
                        deptcode}, this.ReceiveMessageOperationCompleted, userState);
        }
        
        private void OnReceiveMessageOperationCompleted(object arg) {
            if ((this.ReceiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveMessageCompleted(this, new ReceiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HasUnreadMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasUnreadMessage(string userid, string deptcode) {
            object[] results = this.Invoke("HasUnreadMessage", new object[] {
                        userid,
                        deptcode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasUnreadMessageAsync(string userid, string deptcode) {
            this.HasUnreadMessageAsync(userid, deptcode, null);
        }
        
        /// <remarks/>
        public void HasUnreadMessageAsync(string userid, string deptcode, object userState) {
            if ((this.HasUnreadMessageOperationCompleted == null)) {
                this.HasUnreadMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasUnreadMessageOperationCompleted);
            }
            this.InvokeAsync("HasUnreadMessage", new object[] {
                        userid,
                        deptcode}, this.HasUnreadMessageOperationCompleted, userState);
        }
        
        private void OnHasUnreadMessageOperationCompleted(object arg) {
            if ((this.HasUnreadMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasUnreadMessageCompleted(this, new HasUnreadMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveReadedMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PageMsgInfo ReceiveReadedMessage(string userid, string deptcode, string fromids, string dateStart, string dateEnd, int from, int end) {
            object[] results = this.Invoke("ReceiveReadedMessage", new object[] {
                        userid,
                        deptcode,
                        fromids,
                        dateStart,
                        dateEnd,
                        from,
                        end});
            return ((PageMsgInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveReadedMessageAsync(string userid, string deptcode, string fromids, string dateStart, string dateEnd, int from, int end) {
            this.ReceiveReadedMessageAsync(userid, deptcode, fromids, dateStart, dateEnd, from, end, null);
        }
        
        /// <remarks/>
        public void ReceiveReadedMessageAsync(string userid, string deptcode, string fromids, string dateStart, string dateEnd, int from, int end, object userState) {
            if ((this.ReceiveReadedMessageOperationCompleted == null)) {
                this.ReceiveReadedMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveReadedMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveReadedMessage", new object[] {
                        userid,
                        deptcode,
                        fromids,
                        dateStart,
                        dateEnd,
                        from,
                        end}, this.ReceiveReadedMessageOperationCompleted, userState);
        }
        
        private void OnReceiveReadedMessageOperationCompleted(object arg) {
            if ((this.ReceiveReadedMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveReadedMessageCompleted(this, new ReceiveReadedMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveSendedMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PageMsgInfo ReceiveSendedMessage(string userid, string deptcode, string toids, string dateStart, string dateEnd, int from, int end) {
            object[] results = this.Invoke("ReceiveSendedMessage", new object[] {
                        userid,
                        deptcode,
                        toids,
                        dateStart,
                        dateEnd,
                        from,
                        end});
            return ((PageMsgInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveSendedMessageAsync(string userid, string deptcode, string toids, string dateStart, string dateEnd, int from, int end) {
            this.ReceiveSendedMessageAsync(userid, deptcode, toids, dateStart, dateEnd, from, end, null);
        }
        
        /// <remarks/>
        public void ReceiveSendedMessageAsync(string userid, string deptcode, string toids, string dateStart, string dateEnd, int from, int end, object userState) {
            if ((this.ReceiveSendedMessageOperationCompleted == null)) {
                this.ReceiveSendedMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveSendedMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveSendedMessage", new object[] {
                        userid,
                        deptcode,
                        toids,
                        dateStart,
                        dateEnd,
                        from,
                        end}, this.ReceiveSendedMessageOperationCompleted, userState);
        }
        
        private void OnReceiveSendedMessageOperationCompleted(object arg) {
            if ((this.ReceiveSendedMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveSendedMessageCompleted(this, new ReceiveSendedMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveAllMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PageMsgInfo ReceiveAllMessage(string fromids, string toids, string dateStart, string dateEnd, int from, int end) {
            object[] results = this.Invoke("ReceiveAllMessage", new object[] {
                        fromids,
                        toids,
                        dateStart,
                        dateEnd,
                        from,
                        end});
            return ((PageMsgInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveAllMessageAsync(string fromids, string toids, string dateStart, string dateEnd, int from, int end) {
            this.ReceiveAllMessageAsync(fromids, toids, dateStart, dateEnd, from, end, null);
        }
        
        /// <remarks/>
        public void ReceiveAllMessageAsync(string fromids, string toids, string dateStart, string dateEnd, int from, int end, object userState) {
            if ((this.ReceiveAllMessageOperationCompleted == null)) {
                this.ReceiveAllMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveAllMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveAllMessage", new object[] {
                        fromids,
                        toids,
                        dateStart,
                        dateEnd,
                        from,
                        end}, this.ReceiveAllMessageOperationCompleted, userState);
        }
        
        private void OnReceiveAllMessageOperationCompleted(object arg) {
            if ((this.ReceiveAllMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveAllMessageCompleted(this, new ReceiveAllMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllMessageByDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgInfo[] GetAllMessageByDept(string deptCode, int readflag) {
            object[] results = this.Invoke("GetAllMessageByDept", new object[] {
                        deptCode,
                        readflag});
            return ((MsgInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMessageByDeptAsync(string deptCode, int readflag) {
            this.GetAllMessageByDeptAsync(deptCode, readflag, null);
        }
        
        /// <remarks/>
        public void GetAllMessageByDeptAsync(string deptCode, int readflag, object userState) {
            if ((this.GetAllMessageByDeptOperationCompleted == null)) {
                this.GetAllMessageByDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMessageByDeptOperationCompleted);
            }
            this.InvokeAsync("GetAllMessageByDept", new object[] {
                        deptCode,
                        readflag}, this.GetAllMessageByDeptOperationCompleted, userState);
        }
        
        private void OnGetAllMessageByDeptOperationCompleted(object arg) {
            if ((this.GetAllMessageByDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMessageByDeptCompleted(this, new GetAllMessageByDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetMessageReaded", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetMessageReaded(long msgid) {
            object[] results = this.Invoke("SetMessageReaded", new object[] {
                        msgid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetMessageReadedAsync(long msgid) {
            this.SetMessageReadedAsync(msgid, null);
        }
        
        /// <remarks/>
        public void SetMessageReadedAsync(long msgid, object userState) {
            if ((this.SetMessageReadedOperationCompleted == null)) {
                this.SetMessageReadedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMessageReadedOperationCompleted);
            }
            this.InvokeAsync("SetMessageReaded", new object[] {
                        msgid}, this.SetMessageReadedOperationCompleted, userState);
        }
        
        private void OnSetMessageReadedOperationCompleted(object arg) {
            if ((this.SetMessageReadedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMessageReadedCompleted(this, new SetMessageReadedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Doctor Login(string userid, string deptcode, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        userid,
                        deptcode,
                        password});
            return ((Doctor)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string userid, string deptcode, string password) {
            this.LoginAsync(userid, deptcode, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string userid, string deptcode, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        userid,
                        deptcode,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDoctor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Doctor GetDoctor(string userid, string deptcode) {
            object[] results = this.Invoke("GetDoctor", new object[] {
                        userid,
                        deptcode});
            return ((Doctor)(results[0]));
        }
        
        /// <remarks/>
        public void GetDoctorAsync(string userid, string deptcode) {
            this.GetDoctorAsync(userid, deptcode, null);
        }
        
        /// <remarks/>
        public void GetDoctorAsync(string userid, string deptcode, object userState) {
            if ((this.GetDoctorOperationCompleted == null)) {
                this.GetDoctorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDoctorOperationCompleted);
            }
            this.InvokeAsync("GetDoctor", new object[] {
                        userid,
                        deptcode}, this.GetDoctorOperationCompleted, userState);
        }
        
        private void OnGetDoctorOperationCompleted(object arg) {
            if ((this.GetDoctorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDoctorCompleted(this, new GetDoctorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDoctorList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Doctor[] GetDoctorList() {
            object[] results = this.Invoke("GetDoctorList", new object[0]);
            return ((Doctor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDoctorListAsync() {
            this.GetDoctorListAsync(null);
        }
        
        /// <remarks/>
        public void GetDoctorListAsync(object userState) {
            if ((this.GetDoctorListOperationCompleted == null)) {
                this.GetDoctorListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDoctorListOperationCompleted);
            }
            this.InvokeAsync("GetDoctorList", new object[0], this.GetDoctorListOperationCompleted, userState);
        }
        
        private void OnGetDoctorListOperationCompleted(object arg) {
            if ((this.GetDoctorListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDoctorListCompleted(this, new GetDoctorListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeptDoctorList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Doctor[] GetDeptDoctorList(string dept) {
            object[] results = this.Invoke("GetDeptDoctorList", new object[] {
                        dept});
            return ((Doctor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptDoctorListAsync(string dept) {
            this.GetDeptDoctorListAsync(dept, null);
        }
        
        /// <remarks/>
        public void GetDeptDoctorListAsync(string dept, object userState) {
            if ((this.GetDeptDoctorListOperationCompleted == null)) {
                this.GetDeptDoctorListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptDoctorListOperationCompleted);
            }
            this.InvokeAsync("GetDeptDoctorList", new object[] {
                        dept}, this.GetDeptDoctorListOperationCompleted, userState);
        }
        
        private void OnGetDeptDoctorListOperationCompleted(object arg) {
            if ((this.GetDeptDoctorListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptDoctorListCompleted(this, new GetDeptDoctorListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegisterUser(string userId, string password, string username, string sex, string mobile, string department) {
            object[] results = this.Invoke("RegisterUser", new object[] {
                        userId,
                        password,
                        username,
                        sex,
                        mobile,
                        department});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterUserAsync(string userId, string password, string username, string sex, string mobile, string department) {
            this.RegisterUserAsync(userId, password, username, sex, mobile, department, null);
        }
        
        /// <remarks/>
        public void RegisterUserAsync(string userId, string password, string username, string sex, string mobile, string department, object userState) {
            if ((this.RegisterUserOperationCompleted == null)) {
                this.RegisterUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterUserOperationCompleted);
            }
            this.InvokeAsync("RegisterUser", new object[] {
                        userId,
                        password,
                        username,
                        sex,
                        mobile,
                        department}, this.RegisterUserOperationCompleted, userState);
        }
        
        private void OnRegisterUserOperationCompleted(object arg) {
            if ((this.RegisterUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterUserCompleted(this, new RegisterUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgInfo {
        
        private long messageIdField;
        
        private string businessMessageIdField;
        
        private string businessMessageContentField;
        
        private string departMessageidField;
        
        private bool departSendField;
        
        private string userIdField;
        
        private string userNameField;
        
        private string departmentField;
        
        private string deptCodeField;
        
        private string userIdToField;
        
        private string userNameToField;
        
        private string departmentToField;
        
        private string deptToCodeField;
        
        private System.DateTime sendTimeField;
        
        private string messageTitleField;
        
        private string messageContentField;
        
        private string messageTypeField;
        
        private bool hasReadField;
        
        private System.DateTime readTimeField;
        
        private bool hasTimeOutAlertField;
        
        private System.Nullable<long> timeoutMessageidField;
        
        /// <remarks/>
        public long MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessMessageId {
            get {
                return this.businessMessageIdField;
            }
            set {
                this.businessMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessMessageContent {
            get {
                return this.businessMessageContentField;
            }
            set {
                this.businessMessageContentField = value;
            }
        }
        
        /// <remarks/>
        public string DepartMessageid {
            get {
                return this.departMessageidField;
            }
            set {
                this.departMessageidField = value;
            }
        }
        
        /// <remarks/>
        public bool DepartSend {
            get {
                return this.departSendField;
            }
            set {
                this.departSendField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string DeptCode {
            get {
                return this.deptCodeField;
            }
            set {
                this.deptCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserIdTo {
            get {
                return this.userIdToField;
            }
            set {
                this.userIdToField = value;
            }
        }
        
        /// <remarks/>
        public string UserNameTo {
            get {
                return this.userNameToField;
            }
            set {
                this.userNameToField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentTo {
            get {
                return this.departmentToField;
            }
            set {
                this.departmentToField = value;
            }
        }
        
        /// <remarks/>
        public string DeptToCode {
            get {
                return this.deptToCodeField;
            }
            set {
                this.deptToCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
        
        /// <remarks/>
        public string MessageTitle {
            get {
                return this.messageTitleField;
            }
            set {
                this.messageTitleField = value;
            }
        }
        
        /// <remarks/>
        public string MessageContent {
            get {
                return this.messageContentField;
            }
            set {
                this.messageContentField = value;
            }
        }
        
        /// <remarks/>
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool HasRead {
            get {
                return this.hasReadField;
            }
            set {
                this.hasReadField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReadTime {
            get {
                return this.readTimeField;
            }
            set {
                this.readTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool HasTimeOutAlert {
            get {
                return this.hasTimeOutAlertField;
            }
            set {
                this.hasTimeOutAlertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> TimeoutMessageid {
            get {
                return this.timeoutMessageidField;
            }
            set {
                this.timeoutMessageidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Doctor {
        
        private string userIdField;
        
        private string passwordField;
        
        private string userNameField;
        
        private string sexField;
        
        private string mobileField;
        
        private string deptcodeField;
        
        private string departmentField;
        
        private bool isAdminField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Deptcode {
            get {
                return this.deptcodeField;
            }
            set {
                this.deptcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PageMsgInfo {
        
        private MsgInfo[] msgInfosField;
        
        private int msgCountField;
        
        /// <remarks/>
        public MsgInfo[] MsgInfos {
            get {
                return this.msgInfosField;
            }
            set {
                this.msgInfosField = value;
            }
        }
        
        /// <remarks/>
        public int MsgCount {
            get {
                return this.msgCountField;
            }
            set {
                this.msgCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void SendMessageToDeptCompletedEventHandler(object sender, SendMessageToDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageToDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageToDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ReceiveMessageCompletedEventHandler(object sender, ReceiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void HasUnreadMessageCompletedEventHandler(object sender, HasUnreadMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasUnreadMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasUnreadMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ReceiveReadedMessageCompletedEventHandler(object sender, ReceiveReadedMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveReadedMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveReadedMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageMsgInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageMsgInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ReceiveSendedMessageCompletedEventHandler(object sender, ReceiveSendedMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveSendedMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveSendedMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageMsgInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageMsgInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ReceiveAllMessageCompletedEventHandler(object sender, ReceiveAllMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveAllMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveAllMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageMsgInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageMsgInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetAllMessageByDeptCompletedEventHandler(object sender, GetAllMessageByDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMessageByDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMessageByDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void SetMessageReadedCompletedEventHandler(object sender, SetMessageReadedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetMessageReadedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetMessageReadedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Doctor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Doctor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetDoctorCompletedEventHandler(object sender, GetDoctorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDoctorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDoctorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Doctor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Doctor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetDoctorListCompletedEventHandler(object sender, GetDoctorListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDoctorListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDoctorListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Doctor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Doctor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetDeptDoctorListCompletedEventHandler(object sender, GetDeptDoctorListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptDoctorListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptDoctorListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Doctor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Doctor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void RegisterUserCompletedEventHandler(object sender, RegisterUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591