<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Pricing.RuleCenter.Core\Pricing.RuleCenter.Core.csproj" />
    <ProjectReference Include="..\Pricing.RuleCenter.Infrastructure\Pricing.RuleCenter.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

</Project>
