-- ============================================================
-- 统一计价规则中心 - Oracle 11g DDL
-- 生成日期: 2026-05-09
-- 表前缀: PR_  (Pricing Rule)
-- 金额: NUMBER(18,4)   C#: decimal
-- 主键: NUMBER(18,0)    SEQUENCE
-- 布尔: CHAR(1)         Y/N
-- 时间: DATE
-- JSON: CLOB
-- ============================================================

-- ============================================================
-- 一、SEQUENCE
-- ============================================================

CREATE SEQUENCE SEQ_PR_RULE_HEADER       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_VERSION      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_CONDITION    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_ACTION       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_FORMULA_DEF       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_DICT              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_ITEM_GROUP        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_ITEM_GROUP_DETAIL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_PUBLISH      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_CHANGE_LOG   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_APPROVAL     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_TEST_CASE    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RULE_TEST_RUN     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_CHARGE_REQ_LOG    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_CHARGE_TRACE_STEP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_CHARGE_DISC_DTL   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_LIMIT_OCCUPY      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_CHARGE_REVERSE    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- 二、规则配置表
-- ============================================================

-- 2.1 规则头表
CREATE TABLE PR_RULE_HEADER (
    RULE_ID           NUMBER(18,0)    NOT NULL,
    RULE_CODE         VARCHAR2(50)    NOT NULL,
    RULE_NAME         VARCHAR2(200)   NOT NULL,
    RULE_CATEGORY     VARCHAR2(30)    DEFAULT 'MIXED' NOT NULL,
    RULE_SCOPE        VARCHAR2(30)    DEFAULT 'ITEM' NOT NULL,
    ITEM_CODE         VARCHAR2(50),
    ITEM_NAME         VARCHAR2(200),
    GROUP_CODE        VARCHAR2(50),
    PRIORITY          NUMBER(10,0)    DEFAULT 100 NOT NULL,
    CURRENT_VERSION   NUMBER(10,0)    DEFAULT 0 NOT NULL,
    STATUS            VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL,
    IS_ENABLED        CHAR(1)         DEFAULT 'Y' NOT NULL,
    EFFECTIVE_FROM    DATE,
    EFFECTIVE_TO      DATE,
    ROLLBACK_MODE     VARCHAR2(30),
    REMARK            VARCHAR2(1000),
    CREATED_BY        VARCHAR2(50),
    CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY        VARCHAR2(50),
    UPDATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_RULE_HEADER PRIMARY KEY (RULE_ID),
    CONSTRAINT UK_PR_RULE_HEADER_CODE UNIQUE (RULE_CODE),
    CONSTRAINT CK_PR_RH_STATUS CHECK (STATUS IN ('DRAFT','PUBLISHED','DISABLED')),
    CONSTRAINT CK_PR_RH_SCOPE CHECK (RULE_SCOPE IN ('ITEM','GROUP','SCENE')),
    CONSTRAINT CK_PR_RH_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_RULE_HEADER IS '规则头表 - 一条规则的主信息';
COMMENT ON COLUMN PR_RULE_HEADER.RULE_ID IS '主键';
COMMENT ON COLUMN PR_RULE_HEADER.RULE_CODE IS '规则编码，全局唯一';
COMMENT ON COLUMN PR_RULE_HEADER.RULE_NAME IS '规则名称';
COMMENT ON COLUMN PR_RULE_HEADER.RULE_CATEGORY IS '规则类别: DISCOUNT/FORMULA/LIMIT/MIXED';
COMMENT ON COLUMN PR_RULE_HEADER.RULE_SCOPE IS '规则范围: ITEM(单项目)/GROUP(项目组)/SCENE(场景)';
COMMENT ON COLUMN PR_RULE_HEADER.ITEM_CODE IS '项目编码，关联 fin_com_undruginfo.item_code';
COMMENT ON COLUMN PR_RULE_HEADER.ITEM_NAME IS '项目名称';
COMMENT ON COLUMN PR_RULE_HEADER.GROUP_CODE IS '项目组编码，关联 PR_ITEM_GROUP.GROUP_CODE';
COMMENT ON COLUMN PR_RULE_HEADER.PRIORITY IS '优先级，数字越小越先执行';
COMMENT ON COLUMN PR_RULE_HEADER.CURRENT_VERSION IS '当前生效版本号';
COMMENT ON COLUMN PR_RULE_HEADER.STATUS IS '状态: DRAFT/PUBLISHED/DISABLED';
COMMENT ON COLUMN PR_RULE_HEADER.IS_ENABLED IS '是否启用: Y/N';
COMMENT ON COLUMN PR_RULE_HEADER.EFFECTIVE_FROM IS '生效开始时间';
COMMENT ON COLUMN PR_RULE_HEADER.EFFECTIVE_TO IS '生效结束时间';
COMMENT ON COLUMN PR_RULE_HEADER.ROLLBACK_MODE IS '降级/回滚模式: STOP_CHARGE/LEGACY_EQUIVALENT/MANUAL_REVIEW';

CREATE INDEX IDX_PR_RH_ITEM ON PR_RULE_HEADER (ITEM_CODE, IS_ENABLED, STATUS);
CREATE INDEX IDX_PR_RH_GROUP ON PR_RULE_HEADER (GROUP_CODE, IS_ENABLED, STATUS);
CREATE INDEX IDX_PR_RH_EFFECT ON PR_RULE_HEADER (EFFECTIVE_FROM, EFFECTIVE_TO);


-- 2.2 规则版本表
CREATE TABLE PR_RULE_VERSION (
    VERSION_ID        NUMBER(18,0)    NOT NULL,
    RULE_ID           NUMBER(18,0)    NOT NULL,
    VERSION_NO        NUMBER(10,0)    NOT NULL,
    VERSION_STATUS    VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL,
    EFFECTIVE_FROM    DATE,
    EFFECTIVE_TO      DATE,
    RULE_SNAPSHOT     CLOB,
    PUBLISHED_BY      VARCHAR2(50),
    PUBLISHED_AT      DATE,
    PUBLISH_REMARK    VARCHAR2(1000),
    CONSTRAINT PK_PR_RULE_VERSION PRIMARY KEY (VERSION_ID),
    CONSTRAINT UK_PR_RV_RULE_VER UNIQUE (RULE_ID, VERSION_NO),
    CONSTRAINT CK_PR_RV_STATUS CHECK (VERSION_STATUS IN ('DRAFT','PUBLISHED','ROLLED_BACK','DISABLED'))
);

COMMENT ON TABLE  PR_RULE_VERSION IS '规则版本表 - 每次发布生成一个版本';
COMMENT ON COLUMN PR_RULE_VERSION.RULE_SNAPSHOT IS '规则完整快照(JSON)，含条件和动作';
COMMENT ON COLUMN PR_RULE_VERSION.VERSION_STATUS IS '版本状态: DRAFT/PUBLISHED/ROLLED_BACK/DISABLED';

CREATE INDEX IDX_PR_RV_EFFECT ON PR_RULE_VERSION (RULE_ID, EFFECTIVE_FROM, EFFECTIVE_TO);
CREATE UNIQUE INDEX UK_PR_RV_RULE_PUBLISHED
    ON PR_RULE_VERSION (CASE WHEN VERSION_STATUS = 'PUBLISHED' THEN RULE_ID END);


-- 2.2A 缓存版本表
CREATE TABLE PR_CACHE_VERSION (
    CACHE_SCOPE       VARCHAR2(50)    NOT NULL,
    VERSION_NO        NUMBER(18,0)    DEFAULT 0 NOT NULL,
    UPDATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_CACHE_VERSION PRIMARY KEY (CACHE_SCOPE)
);

COMMENT ON TABLE  PR_CACHE_VERSION IS '缓存版本表 - 多实例共享缓存失效版本号';
COMMENT ON COLUMN PR_CACHE_VERSION.CACHE_SCOPE IS '缓存作用域，如 EFFECTIVE_RULES、ACTION_TYPE_ORDER';
COMMENT ON COLUMN PR_CACHE_VERSION.VERSION_NO IS '缓存版本号，失效时递增';


-- 2.3 规则条件表
CREATE TABLE PR_RULE_CONDITION (
    CONDITION_ID      NUMBER(18,0)    NOT NULL,
    RULE_ID           NUMBER(18,0)    NOT NULL,
    VERSION_NO        NUMBER(10,0)    NOT NULL,
    CONDITION_GROUP   VARCHAR2(50)    DEFAULT 'DEFAULT' NOT NULL,
    CONDITION_TYPE    VARCHAR2(50)    NOT NULL,
    OPERATOR_TYPE     VARCHAR2(20)    DEFAULT 'EQ',
    LEFT_KEY          VARCHAR2(100),
    RIGHT_VALUE       VARCHAR2(1000),
    PARAMS_JSON       CLOB,
    SORT_NO           NUMBER(10,0)    DEFAULT 0 NOT NULL,
    IS_ENABLED        CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PR_RULE_CONDITION PRIMARY KEY (CONDITION_ID),
    CONSTRAINT CK_PR_RC_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_RULE_CONDITION IS '规则条件表 - 同组AND，跨组OR';
COMMENT ON COLUMN PR_RULE_CONDITION.CONDITION_GROUP IS '条件组，同组内AND，不同组OR';
COMMENT ON COLUMN PR_RULE_CONDITION.CONDITION_TYPE IS '条件类型: ITEM_MATCH/GROUP_MATCH/VISIT_TYPE_MATCH/CHARGE_SCENE_MATCH/BODY_PART_MATCH/TIME_WINDOW/SAME_DAY/SAME_OPERATION/SAME_PREGNANCY/AGE_MATCH';
COMMENT ON COLUMN PR_RULE_CONDITION.OPERATOR_TYPE IS '比较运算符: EQ/NE/GT/GE/LT/LE/IN/BETWEEN';
COMMENT ON COLUMN PR_RULE_CONDITION.LEFT_KEY IS '左值，如 ITEM_CODE/BODY_PART/AGE';
COMMENT ON COLUMN PR_RULE_CONDITION.RIGHT_VALUE IS '右值，多值用逗号分隔';
COMMENT ON COLUMN PR_RULE_CONDITION.PARAMS_JSON IS '扩展参数(JSON)';

CREATE INDEX IDX_PR_RC_RULE ON PR_RULE_CONDITION (RULE_ID, VERSION_NO, CONDITION_GROUP);


-- 2.4 规则动作表
CREATE TABLE PR_RULE_ACTION (
    ACTION_ID         NUMBER(18,0)    NOT NULL,
    RULE_ID           NUMBER(18,0)    NOT NULL,
    VERSION_NO        NUMBER(10,0)    NOT NULL,
    ACTION_TYPE       VARCHAR2(50)    NOT NULL,
    EXECUTOR_CODE     VARCHAR2(50)    NOT NULL,
    PARAMS_JSON       CLOB,
    EXCLUSIVE_GROUP   VARCHAR2(50),
    SORT_NO           NUMBER(10,0)    DEFAULT 0 NOT NULL,
    ON_ERROR          VARCHAR2(20)    DEFAULT 'STOP' NOT NULL,
    IS_ENABLED        CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PR_RULE_ACTION PRIMARY KEY (ACTION_ID),
    CONSTRAINT CK_PR_RA_ERROR CHECK (ON_ERROR IN ('STOP','SKIP','WARN')),
    CONSTRAINT CK_PR_RA_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_RULE_ACTION IS '规则动作表 - 按SORT_NO顺序执行';
COMMENT ON COLUMN PR_RULE_ACTION.ACTION_TYPE IS '动作类型: CONVERT_QTY/FORMULA_CALC/APPLY_MAX_AMOUNT/APPLY_MIN_AMOUNT/APPLY_DAY_LIMIT_QTY/APPLY_ONCE_LIMIT_QTY/APPLY_TIME_WINDOW_LIMIT/DISCOUNT_EXCEED_TO_ZERO/ADD_CHILD_ITEM/ROUND_QTY';
COMMENT ON COLUMN PR_RULE_ACTION.EXECUTOR_CODE IS '执行器编码，对应C#类';
COMMENT ON COLUMN PR_RULE_ACTION.EXCLUSIVE_GROUP IS '互斥组编码，同组内只执行优先级最高的动作';
COMMENT ON COLUMN PR_RULE_ACTION.ON_ERROR IS '错误处理: STOP/SKIP/WARN';

CREATE INDEX IDX_PR_RA_RULE ON PR_RULE_ACTION (RULE_ID, VERSION_NO, SORT_NO);


-- 2.5 公式定义表
CREATE TABLE PR_FORMULA_DEF (
    FORMULA_ID        NUMBER(18,0)    NOT NULL,
    FORMULA_CODE      VARCHAR2(50)    NOT NULL,
    FORMULA_NAME      VARCHAR2(200)   NOT NULL,
    FORMULA_DESC      VARCHAR2(1000),
    EXECUTOR_CODE     VARCHAR2(50)    NOT NULL,
    PARAM_SCHEMA_JSON CLOB,
    IS_ENABLED        CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK            VARCHAR2(1000),
    CONSTRAINT PK_PR_FORMULA_DEF PRIMARY KEY (FORMULA_ID),
    CONSTRAINT UK_PR_FD_CODE UNIQUE (FORMULA_CODE),
    CONSTRAINT CK_PR_FD_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_FORMULA_DEF IS '公式定义表 - 系统支持的受控公式';
COMMENT ON COLUMN PR_FORMULA_DEF.FORMULA_CODE IS '公式编码，如 INCREMENT_PERCENT/AREA_STEP_INCREMENT';
COMMENT ON COLUMN PR_FORMULA_DEF.EXECUTOR_CODE IS '对应C#执行器类名';
COMMENT ON COLUMN PR_FORMULA_DEF.PARAM_SCHEMA_JSON IS '参数结构说明(JSON)';


-- 2.6 字典表
CREATE TABLE PR_DICT (
    DICT_ID           NUMBER(18,0)    NOT NULL,
    DICT_TYPE         VARCHAR2(50)    NOT NULL,
    DICT_CODE         VARCHAR2(50)    NOT NULL,
    DICT_NAME         VARCHAR2(200)   NOT NULL,
    PARENT_CODE       VARCHAR2(50),
    SORT_NO           NUMBER(10,0)    DEFAULT 0 NOT NULL,
    IS_ENABLED        CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK            VARCHAR2(500),
    CONSTRAINT PK_PR_DICT PRIMARY KEY (DICT_ID),
    CONSTRAINT UK_PR_DICT_TYPE_CODE UNIQUE (DICT_TYPE, DICT_CODE),
    CONSTRAINT CK_PR_DICT_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_DICT IS '字典表 - 计价类型/单位/部位/规则类别等';
COMMENT ON COLUMN PR_DICT.DICT_TYPE IS '字典类型: PRICING_TYPE/PRICING_UNIT/BODY_PART/RULE_CATEGORY/CHARGE_SCENE/FORMULA_TYPE/ACTION_TYPE/CONDITION_TYPE';
COMMENT ON COLUMN PR_DICT.PARENT_CODE IS '父级编码，用于二级字典';

CREATE INDEX IDX_PR_DICT_TYPE ON PR_DICT (DICT_TYPE, SORT_NO);


-- ============================================================
-- 三、项目组表
-- ============================================================

-- 3.1 项目组表
CREATE TABLE PR_ITEM_GROUP (
    GROUP_ID          NUMBER(18,0)    NOT NULL,
    GROUP_CODE        VARCHAR2(50)    NOT NULL,
    GROUP_NAME        VARCHAR2(200)   NOT NULL,
    GROUP_TYPE        VARCHAR2(50)    NOT NULL,
    IS_ENABLED        CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK            VARCHAR2(1000),
    CREATED_BY        VARCHAR2(50),
    CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY        VARCHAR2(50),
    UPDATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_ITEM_GROUP PRIMARY KEY (GROUP_ID),
    CONSTRAINT UK_PR_IG_CODE UNIQUE (GROUP_CODE),
    CONSTRAINT CK_PR_IG_TYPE CHECK (GROUP_TYPE IN ('MUTEX','ADDON','REPLACE','LIMIT')),
    CONSTRAINT CK_PR_IG_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_ITEM_GROUP IS '项目组表 - 同组互斥/加收/替换/限制';
COMMENT ON COLUMN PR_ITEM_GROUP.GROUP_TYPE IS '组类型: MUTEX(互斥)/ADDON(加收)/REPLACE(替换)/LIMIT(共用限额)';


-- 3.2 项目组明细表
CREATE TABLE PR_ITEM_GROUP_DETAIL (
    DETAIL_ID         NUMBER(18,0)    NOT NULL,
    GROUP_ID          NUMBER(18,0)    NOT NULL,
    ITEM_CODE         VARCHAR2(50)    NOT NULL,
    ITEM_NAME         VARCHAR2(200),
    ROLE_TYPE         VARCHAR2(50)    DEFAULT 'MAIN' NOT NULL,
    SORT_NO           NUMBER(10,0)    DEFAULT 0 NOT NULL,
    IS_ENABLED        CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PR_ITEM_GROUP_DETAIL PRIMARY KEY (DETAIL_ID),
    CONSTRAINT CK_PR_IGD_ROLE CHECK (ROLE_TYPE IN ('MAIN','ADDON','REPLACE_TARGET')),
    CONSTRAINT CK_PR_IGD_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_ITEM_GROUP_DETAIL IS '项目组明细表';
COMMENT ON COLUMN PR_ITEM_GROUP_DETAIL.ROLE_TYPE IS '角色: MAIN(主项目)/ADDON(加收)/REPLACE_TARGET(替换目标)';

CREATE INDEX IDX_PR_IGD_GROUP ON PR_ITEM_GROUP_DETAIL (GROUP_ID);
CREATE INDEX IDX_PR_IGD_ITEM ON PR_ITEM_GROUP_DETAIL (ITEM_CODE);


-- ============================================================
-- 四、规则发布与审计表
-- ============================================================

-- 4.1 规则发布表
CREATE TABLE PR_RULE_PUBLISH (
    PUBLISH_ID        NUMBER(18,0)    NOT NULL,
    PUBLISH_NO        VARCHAR2(50)    NOT NULL,
    RULE_ID           NUMBER(18,0)    NOT NULL,
    FROM_VERSION      NUMBER(10,0),
    TO_VERSION        NUMBER(10,0)    NOT NULL,
    ACTION_TYPE       VARCHAR2(30)    NOT NULL,
    PUBLISHED_BY      VARCHAR2(50),
    PUBLISHED_AT      DATE            DEFAULT SYSDATE NOT NULL,
    REMARK            VARCHAR2(1000),
    CONSTRAINT PK_PR_RULE_PUBLISH PRIMARY KEY (PUBLISH_ID),
    CONSTRAINT UK_PR_RP_NO UNIQUE (PUBLISH_NO),
    CONSTRAINT CK_PR_RP_ACTION CHECK (ACTION_TYPE IN ('PUBLISH','DISABLE','ROLLBACK'))
);

COMMENT ON TABLE  PR_RULE_PUBLISH IS '规则发布表 - 记录发布/停用/回滚';
COMMENT ON COLUMN PR_RULE_PUBLISH.ACTION_TYPE IS '操作类型: PUBLISH/DISABLE/ROLLBACK';

CREATE INDEX IDX_PR_RP_RULE ON PR_RULE_PUBLISH (RULE_ID, PUBLISHED_AT);


-- 4.2 规则变更日志表
CREATE TABLE PR_RULE_CHANGE_LOG (
    CHANGE_ID         NUMBER(18,0)    NOT NULL,
    RULE_ID           NUMBER(18,0)    NOT NULL,
    VERSION_NO        NUMBER(10,0),
    CHANGE_TYPE       VARCHAR2(30)    NOT NULL,
    CHANGE_SUMMARY    VARCHAR2(1000),
    BEFORE_SNAPSHOT   CLOB,
    AFTER_SNAPSHOT    CLOB,
    CHANGED_BY        VARCHAR2(50),
    CHANGED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    SOURCE_SYSTEM     VARCHAR2(50),
    CONSTRAINT PK_PR_RULE_CHANGE_LOG PRIMARY KEY (CHANGE_ID),
    CONSTRAINT CK_PR_RCL_TYPE CHECK (CHANGE_TYPE IN (
        'CREATE','UPDATE','DELETE',
        'CREATE_RULE','UPDATE_RULE',
        'SAVE_CONDITIONS','SAVE_ACTIONS',
        'CREATE_FORMULA','UPDATE_FORMULA','TOGGLE_FORMULA',
        'CREATE_DICT','UPDATE_DICT','DELETE_DICT',
        'PUBLISH','DISABLE','ROLLBACK'
    ))
);

COMMENT ON TABLE  PR_RULE_CHANGE_LOG IS '规则变更日志表 - 谁改了什么';

CREATE INDEX IDX_PR_RCL_RULE ON PR_RULE_CHANGE_LOG (RULE_ID, CHANGED_AT);


-- 4.3 规则审核表
CREATE TABLE PR_RULE_APPROVAL (
    APPROVAL_ID      NUMBER(18,0)    NOT NULL,
    RULE_ID          NUMBER(18,0)    NOT NULL,
    VERSION_NO       NUMBER(10,0),
    ACTION_TYPE      VARCHAR2(30)    NOT NULL,
    APPROVAL_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    SUBMITTED_BY     VARCHAR2(50)    NOT NULL,
    SUBMITTED_AT     DATE            DEFAULT SYSDATE NOT NULL,
    REVIEWED_BY      VARCHAR2(50),
    REVIEWED_AT      DATE,
    REVIEW_COMMENT   VARCHAR2(1000),
    CONSTRAINT PK_PR_RULE_APPROVAL PRIMARY KEY (APPROVAL_ID),
    CONSTRAINT CK_PR_RAP_ACTION CHECK (ACTION_TYPE IN ('PUBLISH','DISABLE','ROLLBACK')),
    CONSTRAINT CK_PR_RAP_STATUS CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED'))
);

COMMENT ON TABLE  PR_RULE_APPROVAL IS '规则审核表 - 发布/停用/回滚前审核记录';
COMMENT ON COLUMN PR_RULE_APPROVAL.APPROVAL_STATUS IS '审核状态: PENDING/APPROVED/REJECTED';
COMMENT ON COLUMN PR_RULE_APPROVAL.ACTION_TYPE IS '审核动作: PUBLISH/DISABLE/ROLLBACK';

CREATE INDEX IDX_PR_RAP_RULE ON PR_RULE_APPROVAL (RULE_ID, VERSION_NO, APPROVAL_STATUS);
CREATE UNIQUE INDEX UK_PR_RAP_PENDING
ON PR_RULE_APPROVAL (
    CASE WHEN APPROVAL_STATUS = 'PENDING' THEN RULE_ID END,
    CASE WHEN APPROVAL_STATUS = 'PENDING' THEN VERSION_NO END,
    CASE WHEN APPROVAL_STATUS = 'PENDING' THEN ACTION_TYPE END
);


-- 4.4 规则测试用例表
CREATE TABLE PR_RULE_TEST_CASE (
    TEST_CASE_ID     NUMBER(18,0)    NOT NULL,
    RULE_ID          NUMBER(18,0)    NOT NULL,
    VERSION_NO       NUMBER(10,0)    NOT NULL,
    CASE_NAME        VARCHAR2(200)   NOT NULL,
    INPUT_JSON       CLOB,
    EXPECTED_JSON    CLOB,
    IS_ENABLED       CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_BY       VARCHAR2(50),
    CREATED_AT       DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_RULE_TEST_CASE PRIMARY KEY (TEST_CASE_ID),
    CONSTRAINT CK_PR_RTC_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

COMMENT ON TABLE  PR_RULE_TEST_CASE IS '规则测试用例表 - 发布前验证输入与期望结果';
COMMENT ON COLUMN PR_RULE_TEST_CASE.INPUT_JSON IS '测试输入(JSON)';
COMMENT ON COLUMN PR_RULE_TEST_CASE.EXPECTED_JSON IS '期望输出(JSON)';

CREATE INDEX IDX_PR_RTC_RULE ON PR_RULE_TEST_CASE (RULE_ID, VERSION_NO, IS_ENABLED);


-- 4.5 规则测试运行表
CREATE TABLE PR_RULE_TEST_RUN (
    TEST_RUN_ID      NUMBER(18,0)    NOT NULL,
    TEST_CASE_ID     NUMBER(18,0)    NOT NULL,
    RULE_ID          NUMBER(18,0)    NOT NULL,
    ACTUAL_JSON      CLOB,
    IS_PASS          CHAR(1)         DEFAULT 'N' NOT NULL,
    RUN_AT           DATE            DEFAULT SYSDATE NOT NULL,
    RUN_BY           VARCHAR2(50),
    ERROR_MESSAGE    VARCHAR2(2000),
    CONSTRAINT PK_PR_RULE_TEST_RUN PRIMARY KEY (TEST_RUN_ID),
    CONSTRAINT CK_PR_RTR_PASS CHECK (IS_PASS IN ('Y','N'))
);

COMMENT ON TABLE  PR_RULE_TEST_RUN IS '规则测试运行表 - 记录测试用例每次执行结果';
COMMENT ON COLUMN PR_RULE_TEST_RUN.ACTUAL_JSON IS '实际输出(JSON)';
COMMENT ON COLUMN PR_RULE_TEST_RUN.IS_PASS IS '是否通过: Y/N';

CREATE INDEX IDX_PR_RTR_CASE ON PR_RULE_TEST_RUN (TEST_CASE_ID, RUN_AT);
CREATE INDEX IDX_PR_RTR_RULE ON PR_RULE_TEST_RUN (RULE_ID, RUN_AT);


-- ============================================================
-- 五、计价追溯表
-- ============================================================

-- 5.1 计价请求日志表
CREATE TABLE PR_CHARGE_REQUEST_LOG (
    REQUEST_ID            NUMBER(18,0)    NOT NULL,
    REQUEST_NO            VARCHAR2(50)    NOT NULL,
    BUSINESS_REQUEST_NO   VARCHAR2(80),
    REQUEST_FINGERPRINT   VARCHAR2(128),
    TRACE_ID              VARCHAR2(50),
    CALL_TYPE             VARCHAR2(20)    NOT NULL,
    BUSINESS_STATUS       VARCHAR2(30)    NOT NULL,
    SOURCE_SYSTEM         VARCHAR2(50)    NOT NULL,
    SOURCE_TERMINAL       VARCHAR2(100),
    PATIENT_ID            VARCHAR2(50),
    VISIT_ID              VARCHAR2(50),
    CHARGE_SCENE          VARCHAR2(50),
    CHARGE_NO             VARCHAR2(50),
    CHARGE_DETAIL_NO      VARCHAR2(50),
    RESULT_GROUP_NO       VARCHAR2(80),
    ITEM_CODE             VARCHAR2(50),
    ITEM_NAME             VARCHAR2(200),
    INPUT_QTY             NUMBER(18,4),
    INPUT_UNIT            VARCHAR2(50),
    BODY_PART_CODE        VARCHAR2(50),
    BUSINESS_CHARGE_TIME  DATE,
    PRICE_VERSION         VARCHAR2(50),
    REQUEST_JSON          CLOB,
    RESPONSE_JSON         CLOB,
    REQUEST_AT            DATE            DEFAULT SYSDATE NOT NULL,
    RESPONSE_AT           DATE,
    IS_SUCCESS            CHAR(1)         DEFAULT 'N' NOT NULL,
    ERROR_MESSAGE         VARCHAR2(2000),
    CONSTRAINT PK_PR_CHARGE_REQ_LOG PRIMARY KEY (REQUEST_ID),
    CONSTRAINT UK_PR_CRL_NO UNIQUE (REQUEST_NO),
    CONSTRAINT CK_PR_CRL_CALL CHECK (CALL_TYPE IN ('SIMULATE','CONFIRM','COMMIT','CANCEL','REVERSE')),
    CONSTRAINT CK_PR_CRL_STATUS CHECK (BUSINESS_STATUS IN ('SIMULATED','CONFIRM_PENDING','CONFIRMED','COMMITTED','CANCELLED','EXPIRED','REVERSED','FAILED')),
    CONSTRAINT CK_PR_CRL_SUCCESS CHECK (IS_SUCCESS IN ('Y','N'))
);

COMMENT ON TABLE  PR_CHARGE_REQUEST_LOG IS '计价请求日志表 - 每次试算或确认计价的完整记录';
COMMENT ON COLUMN PR_CHARGE_REQUEST_LOG.BUSINESS_REQUEST_NO IS '调用方稳定业务号，confirm重试必须复用';
COMMENT ON COLUMN PR_CHARGE_REQUEST_LOG.REQUEST_FINGERPRINT IS '规范化请求指纹，用于幂等参数一致性校验';
COMMENT ON COLUMN PR_CHARGE_REQUEST_LOG.BUSINESS_STATUS IS '业务状态: SIMULATED/CONFIRM_PENDING/CONFIRMED/COMMITTED/CANCELLED/EXPIRED/REVERSED/FAILED';
COMMENT ON COLUMN PR_CHARGE_REQUEST_LOG.BUSINESS_CHARGE_TIME IS '业务收费发生时间，非技术请求时间';
COMMENT ON COLUMN PR_CHARGE_REQUEST_LOG.RESULT_GROUP_NO IS '主子项目同组结果号';

CREATE UNIQUE INDEX UK_PR_CRL_BIZ ON PR_CHARGE_REQUEST_LOG (SOURCE_SYSTEM, BUSINESS_REQUEST_NO, CALL_TYPE);
CREATE INDEX IDX_PR_CRL_TRACE ON PR_CHARGE_REQUEST_LOG (TRACE_ID);
CREATE INDEX IDX_PR_CRL_PATIENT ON PR_CHARGE_REQUEST_LOG (PATIENT_ID, REQUEST_AT);
CREATE INDEX IDX_PR_CRL_CHARGE ON PR_CHARGE_REQUEST_LOG (CHARGE_NO, ITEM_CODE);
CREATE INDEX IDX_PR_CRL_STATUS ON PR_CHARGE_REQUEST_LOG (BUSINESS_STATUS, REQUEST_AT);


-- 5.2 计价步骤日志表
CREATE TABLE PR_CHARGE_TRACE_STEP (
    STEP_ID           NUMBER(18,0)    NOT NULL,
    REQUEST_ID        NUMBER(18,0)    NOT NULL,
    TRACE_ID          VARCHAR2(50),
    STEP_NO           NUMBER(10,0)    NOT NULL,
    STEP_NAME         VARCHAR2(100)   NOT NULL,
    STEP_TYPE         VARCHAR2(50)    NOT NULL,
    RULE_ID           NUMBER(18,0),
    RULE_VERSION_NO   NUMBER(10,0),
    INPUT_SNAPSHOT    CLOB,
    OUTPUT_SNAPSHOT   CLOB,
    STEP_DESC         VARCHAR2(2000),
    CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_CHARGE_TRACE_STEP PRIMARY KEY (STEP_ID),
    CONSTRAINT CK_PR_CTS_TYPE CHECK (STEP_TYPE IN ('MATCH','CONVERT','FORMULA','LIMIT','DISCOUNT','VALIDATE','ERROR'))
);

COMMENT ON TABLE  PR_CHARGE_TRACE_STEP IS '计价步骤日志表 - 按步骤记录计算过程';
COMMENT ON COLUMN PR_CHARGE_TRACE_STEP.STEP_TYPE IS '步骤类型: MATCH/CONVERT/FORMULA/LIMIT/DISCOUNT/VALIDATE/ERROR';

CREATE INDEX IDX_PR_CTS_REQ ON PR_CHARGE_TRACE_STEP (REQUEST_ID, STEP_NO);
CREATE INDEX IDX_PR_CTS_TRACE ON PR_CHARGE_TRACE_STEP (TRACE_ID);


-- 5.3 折价结果明细表
CREATE TABLE PR_CHARGE_DISCOUNT_DETAIL (
    DISCOUNT_ID       NUMBER(18,0)    NOT NULL,
    REQUEST_ID        NUMBER(18,0)    NOT NULL,
    TRACE_ID          VARCHAR2(50),
    CHARGE_NO         VARCHAR2(50),
    CHARGE_DETAIL_NO  VARCHAR2(50),
    PATIENT_ID        VARCHAR2(50),
    VISIT_ID          VARCHAR2(50),
    ITEM_CODE         VARCHAR2(50),
    ITEM_NAME         VARCHAR2(200),
    RULE_ID           NUMBER(18,0),
    RULE_VERSION_NO   NUMBER(10,0),
    DISCOUNT_TYPE     VARCHAR2(50),
    STATUS            VARCHAR2(30)    DEFAULT 'PENDING' NOT NULL,
    RESULT_GROUP_NO   VARCHAR2(80),
    PARENT_DISCOUNT_ID NUMBER(18,0),
    PART_SEQ          NUMBER(10,0),
    ORIGINAL_QTY      NUMBER(18,4),
    CONVERTED_QTY     NUMBER(18,4),
    FINAL_QTY         NUMBER(18,4),
    UNIT_PRICE        NUMBER(18,4),
    ORIGINAL_AMT      NUMBER(18,4),
    CALCULATED_AMT    NUMBER(18,4),
    FINAL_AMT         NUMBER(18,4),
    DISCOUNT_AMT      NUMBER(18,4),
    REASON_CODE       VARCHAR2(50),
    REASON_DESC       VARCHAR2(2000),
    LIMIT_BASE_INFO   CLOB,
    OCCURRED_AT       DATE            DEFAULT SYSDATE NOT NULL,
    CONFIRMED_BY      VARCHAR2(50),
    COMMITTED_AT      DATE,
    CANCELLED_AT      DATE,
    EXPIRED_AT        DATE,
    REVERSED_AT       DATE,
    CONSTRAINT PK_PR_CHARGE_DISC_DTL PRIMARY KEY (DISCOUNT_ID),
    CONSTRAINT CK_PR_CDD_STATUS CHECK (STATUS IN ('PENDING','CONFIRMED','COMMITTED','CANCELLED','EXPIRED','REVERSED'))
);

COMMENT ON TABLE  PR_CHARGE_DISCOUNT_DETAIL IS '折价结果明细表 - 最终折价/封顶/公式调整记录';
COMMENT ON COLUMN PR_CHARGE_DISCOUNT_DETAIL.RESULT_GROUP_NO IS '主子项目同组结果号';
COMMENT ON COLUMN PR_CHARGE_DISCOUNT_DETAIL.PARENT_DISCOUNT_ID IS '子项目关联主项目明细ID';
COMMENT ON COLUMN PR_CHARGE_DISCOUNT_DETAIL.PART_SEQ IS '多部位/多肿物明细序号';
COMMENT ON COLUMN PR_CHARGE_DISCOUNT_DETAIL.UNIT_PRICE IS '权威单价(从物价主表读取)';
COMMENT ON COLUMN PR_CHARGE_DISCOUNT_DETAIL.DISCOUNT_AMT IS '折价金额 = ORIGINAL_AMT - FINAL_AMT';

CREATE INDEX IDX_PR_CDD_REQ ON PR_CHARGE_DISCOUNT_DETAIL (REQUEST_ID);
CREATE INDEX IDX_PR_CDD_PATIENT ON PR_CHARGE_DISCOUNT_DETAIL (PATIENT_ID, OCCURRED_AT);
CREATE INDEX IDX_PR_CDD_CHARGE ON PR_CHARGE_DISCOUNT_DETAIL (CHARGE_NO, CHARGE_DETAIL_NO);
CREATE INDEX IDX_PR_CDD_ITEM ON PR_CHARGE_DISCOUNT_DETAIL (ITEM_CODE, OCCURRED_AT);
CREATE INDEX IDX_PR_CDD_STATUS ON PR_CHARGE_DISCOUNT_DETAIL (STATUS);


-- ============================================================
-- 六、并发控制与冲正表
-- ============================================================

-- 6.1 限额占用表
CREATE TABLE PR_LIMIT_OCCUPY (
    OCCUPY_ID             NUMBER(18,0)    NOT NULL,
    REQUEST_ID            NUMBER(18,0)    NOT NULL,
    TRACE_ID              VARCHAR2(50),
    PATIENT_ID            VARCHAR2(50)    NOT NULL,
    ITEM_CODE             VARCHAR2(50),
    CHARGE_DETAIL_NO      VARCHAR2(50),
    RESULT_GROUP_NO       VARCHAR2(80),
    RULE_ID               NUMBER(18,0),
    RULE_VERSION_NO       NUMBER(10,0),
    LIMIT_TYPE            VARCHAR2(50)    NOT NULL,
    LIMIT_KEY             VARCHAR2(200)   NOT NULL,
    OCCUPY_QTY            NUMBER(18,4)    DEFAULT 0 NOT NULL,
    OCCUPY_AMT            NUMBER(18,4)    DEFAULT 0 NOT NULL,
    OCCUPY_TYPE           VARCHAR2(20)    DEFAULT 'CHARGE' NOT NULL,
    ORIGINAL_OCCUPY_ID    NUMBER(18,0),
    BUSINESS_CHARGE_TIME  DATE            NOT NULL,
    LIMIT_DIMENSION_CODE  VARCHAR2(200),
    PART_SEQ              NUMBER(10,0),
    STATUS                VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    OCCUPIED_AT           DATE            DEFAULT SYSDATE NOT NULL,
    CONFIRMED_AT          DATE,
    EXPIRE_AT             DATE,
    CONSTRAINT PK_PR_LIMIT_OCCUPY PRIMARY KEY (OCCUPY_ID),
    CONSTRAINT CK_PR_LO_LIMIT_TYPE CHECK (LIMIT_TYPE IN ('DAY_QTY','DAY_AMOUNT','ONCE_QTY','TIME_WINDOW','SAME_OPERATION','SAME_PREGNANCY','SAME_GROUP')),
    CONSTRAINT CK_PR_LO_OCCUPY_TYPE CHECK (OCCUPY_TYPE IN ('CHARGE','REVERSE')),
    CONSTRAINT CK_PR_LO_STATUS CHECK (STATUS IN ('PENDING','CONFIRMED','CANCELLED','REVERSED','EXPIRED'))
);

COMMENT ON TABLE  PR_LIMIT_OCCUPY IS '限额占用表 - 防止多渠道并发突破限额';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.CHARGE_DETAIL_NO IS '收费明细号，用于同项目多明细退费时精确释放原占额';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.RESULT_GROUP_NO IS '主子项目同组结果号，用于主子项目退费时原子释放占额';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.LIMIT_KEY IS '限额维度键，由LimitKeyGenerator自动生成';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.OCCUPY_QTY IS '占用数量，退费时为负数';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.OCCUPY_AMT IS '占用金额，退费时为负数';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.ORIGINAL_OCCUPY_ID IS '关联原占用记录ID(退费时填写)';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.BUSINESS_CHARGE_TIME IS '业务收费发生时间，用于时间窗口累计';
COMMENT ON COLUMN PR_LIMIT_OCCUPY.LIMIT_DIMENSION_CODE IS '限额查询维度，如患者+项目';

CREATE INDEX IDX_PR_LO_REQ ON PR_LIMIT_OCCUPY (REQUEST_ID);
CREATE INDEX IDX_PR_LO_KEY ON PR_LIMIT_OCCUPY (LIMIT_KEY, STATUS);
CREATE INDEX IDX_PR_LO_DIM ON PR_LIMIT_OCCUPY (LIMIT_DIMENSION_CODE, BUSINESS_CHARGE_TIME, STATUS);
CREATE INDEX IDX_PR_LO_PATIENT ON PR_LIMIT_OCCUPY (PATIENT_ID, ITEM_CODE, BUSINESS_CHARGE_TIME);
CREATE INDEX IDX_PR_LO_EXPIRE ON PR_LIMIT_OCCUPY (STATUS, EXPIRE_AT);


-- 6.2 限额锁表
CREATE TABLE PR_LIMIT_LOCK (
    LOCK_KEY          VARCHAR2(200)   NOT NULL,
    LOCK_DESC         VARCHAR2(500),
    UPDATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_LIMIT_LOCK PRIMARY KEY (LOCK_KEY)
);

COMMENT ON TABLE  PR_LIMIT_LOCK IS '限额锁表 - SELECT FOR UPDATE 锁定维度';
COMMENT ON COLUMN PR_LIMIT_LOCK.LOCK_KEY IS '锁键，格式: {类型前缀}:{维度值}，如 TW:{patientId}:{itemCode}:{yyyyMMddHH}';


-- 6.3 计价冲正日志表
CREATE TABLE PR_CHARGE_REVERSE_LOG (
    REVERSE_ID            NUMBER(18,0)    NOT NULL,
    ORIGINAL_REQUEST_ID   NUMBER(18,0)    NOT NULL,
    REVERSE_REQUEST_ID    NUMBER(18,0),
    CHARGE_NO             VARCHAR2(50),
    REVERSE_NO            VARCHAR2(50)    NOT NULL,
    ITEM_CODE             VARCHAR2(50),
    CHARGE_DETAIL_NO      VARCHAR2(50),
    PART_SEQ              NUMBER(10,0),
    REVERSE_QTY           NUMBER(18,4),
    REVERSE_AMT           NUMBER(18,4),
    REVERSE_REASON        VARCHAR2(1000),
    REVERSED_BY           VARCHAR2(50),
    REVERSED_AT           DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_CHARGE_REVERSE PRIMARY KEY (REVERSE_ID)
);

COMMENT ON TABLE  PR_CHARGE_REVERSE_LOG IS '计价冲正日志表 - 退费/作废/撤销审计';
COMMENT ON COLUMN PR_CHARGE_REVERSE_LOG.CHARGE_DETAIL_NO IS '被退费或冲正的原收费明细号';
COMMENT ON COLUMN PR_CHARGE_REVERSE_LOG.PART_SEQ IS '多部位/多肿物明细序号';

CREATE INDEX IDX_PR_CRV_ORIG ON PR_CHARGE_REVERSE_LOG (ORIGINAL_REQUEST_ID);
CREATE INDEX IDX_PR_CRV_CHARGE ON PR_CHARGE_REVERSE_LOG (CHARGE_NO);
CREATE UNIQUE INDEX UK_PR_CRV_NO ON PR_CHARGE_REVERSE_LOG (ORIGINAL_REQUEST_ID, REVERSE_NO);
