-- ============================================================
-- 统一计价规则中心 - 字典数据初始化
-- ============================================================

-- ============================================================
-- 一、规则类别 RULE_CATEGORY
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'RULE_CATEGORY', 'DISCOUNT', '折价规则', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'RULE_CATEGORY', 'FORMULA', '公式计价', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'RULE_CATEGORY', 'LIMIT', '数量/金额限制', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'RULE_CATEGORY', 'MIXED', '混合规则', 4, 'Y');


-- ============================================================
-- 二、条件类型 CONDITION_TYPE
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'ITEM_MATCH', '项目匹配', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'GROUP_MATCH', '项目组匹配', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'VISIT_TYPE_MATCH', '就诊类型匹配', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'CHARGE_SCENE_MATCH', '收费场景匹配', 4, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'BODY_PART_MATCH', '部位匹配', 5, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'TIME_WINDOW', '时间窗口', 6, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'SAME_DAY', '同日', 7, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'SAME_OPERATION', '同手术', 8, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'SAME_PREGNANCY', '同胎次', 9, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CONDITION_TYPE', 'AGE_MATCH', '年龄匹配', 10, 'Y');


-- ============================================================
-- 三、动作类型 ACTION_TYPE
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'CONVERT_QTY', '单位换算', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'FORMULA_CALC', '公式计算', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'APPLY_MIN_AMOUNT', '金额下限', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'APPLY_MAX_AMOUNT', '金额上限', 4, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'APPLY_DAY_LIMIT_QTY', '单日数量限制', 5, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'APPLY_ONCE_LIMIT_QTY', '单次数量限制', 6, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'APPLY_TIME_WINDOW_LIMIT', '时间窗口数量限制', 7, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'DISCOUNT_EXCEED_TO_ZERO', '超出部分折价为0', 8, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'ADD_CHILD_ITEM', '子项加收', 9, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'ROUND_QTY', '数量取整', 10, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'ACTION_TYPE', 'SAME_GROUP_MUTEX', '同组互斥封顶', 11, 'Y');


-- ============================================================
-- 四、收费场景 CHARGE_SCENE
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CHARGE_SCENE', 'OUTPATIENT', '门诊', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CHARGE_SCENE', 'INPATIENT', '住院', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CHARGE_SCENE', 'EMERGENCY', '急诊', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CHARGE_SCENE', 'SELF_SERVICE', '自助机', 4, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'CHARGE_SCENE', 'WECHAT', '微信', 5, 'Y');


-- ============================================================
-- 五、计价单位 PRICING_UNIT
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'PRICING_UNIT', 'PART', '部位', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'PRICING_UNIT', 'ITEM', '项', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'PRICING_UNIT', 'CM2', '平方厘米', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'PRICING_UNIT', 'PERCENT_BSA', '%体表面积', 4, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'PRICING_UNIT', 'LESION', '肿物', 5, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'PRICING_UNIT', 'EACH', '个/次', 6, 'Y');


-- ============================================================
-- 六、身体部位 BODY_PART
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'BODY_PART', 'HEAD_FACE', '头面部', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'BODY_PART', 'TRUNK', '躯干部', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'BODY_PART', 'LIMB', '四肢', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'BODY_PART', 'BODY_SURFACE', '体表', 4, 'Y');


-- ============================================================
-- 七、公式类型 FORMULA_TYPE
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'FORMULA_TYPE', 'UNIT_PRICE_TIMES_QTY', '单价×数量', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'FORMULA_TYPE', 'INCREMENT_PERCENT', '固定比例递增', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'FORMULA_TYPE', 'AREA_STEP_INCREMENT', '面积分段递增', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'FORMULA_TYPE', 'CONVERT_QTY_BY_PART', '分部位单位换算', 4, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'FORMULA_TYPE', 'CHILD_ITEM_PERCENT', '子项比例加收', 5, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'FORMULA_TYPE', 'CEILING_AMOUNT', '金额封顶', 6, 'Y');


-- ============================================================
-- 八、比较运算符 OPERATOR_TYPE
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'EQ', '等于', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'NE', '不等于', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'GT', '大于', 3, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'GE', '大于等于', 4, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'LT', '小于', 5, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'LE', '小于等于', 6, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'IN', '包含', 7, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'OPERATOR_TYPE', 'BETWEEN', '范围', 8, 'Y');


-- ============================================================
-- 九、规则范围 RULE_SCOPE
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'RULE_SCOPE', 'ITEM', '单项目', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'RULE_SCOPE', 'GROUP', '项目组', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'RULE_SCOPE', 'SCENE', '场景', 3, 'Y');


-- ============================================================
-- 十、来源系统 SOURCE_SYSTEM
-- ============================================================
INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'SOURCE_SYSTEM', 'HIS', 'HIS系统', 1, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'SOURCE_SYSTEM', 'SELF_MACHINE', '自助机', 2, 'Y');

INSERT INTO PR_DICT (DICT_ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_NO, IS_ENABLED)
VALUES (SEQ_PR_DICT.NEXTVAL, 'SOURCE_SYSTEM', 'WECHAT', '微信公众号', 3, 'Y');


COMMIT;
