-- ============================================================
-- 配置优先计价规则平台 - 新作者模型与运行时包 DDL
-- 适用版本: Oracle 11g
-- 说明:
--   1. 当前 src 仍在开发阶段，本脚本引入新三模型和运行时包表。
--   2. 旧 PR_RULE_* 表不再作为新平台作者入口，仅保留迁移和历史参考用途。
--   3. 本脚本同时补齐计价追溯链的运行时包来源字段。
-- ============================================================

-- ============================================================
-- 一、SEQUENCE
-- ============================================================

CREATE SEQUENCE SEQ_PR_TEMPLATE              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_TEMPLATE_VERSION      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_TEMPLATE_PARAM_DEF    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_TEMPLATE_STEP_DEF     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_TEMPLATE_SCOPE_DEF    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_POLICY                START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_POLICY_VERSION        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_POLICY_BINDING        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_POLICY_SCOPE          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_POLICY_PARAM          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_POLICY_REVIEW         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RUNTIME_PACKAGE       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RUNTIME_PKG_POLICY    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RUNTIME_RULE          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RUNTIME_CONDITION     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PR_RUNTIME_ACTION        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- 二、模板模型
-- ============================================================

CREATE TABLE PR_TEMPLATE (
    TEMPLATE_ID          NUMBER(18,0)   NOT NULL,
    TEMPLATE_CODE        VARCHAR2(60)   NOT NULL,
    TEMPLATE_NAME        VARCHAR2(200)  NOT NULL,
    CATEGORY             VARCHAR2(30)   NOT NULL,
    RISK_LEVEL           VARCHAR2(30)   NOT NULL,
    EXPRESSION_MODE      VARCHAR2(30)   NOT NULL,
    STATUS               VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_NO   NUMBER(10,0)   DEFAULT 0 NOT NULL,
    CREATED_BY           VARCHAR2(50),
    CREATED_AT           DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY           VARCHAR2(50),
    UPDATED_AT           DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_TEMPLATE PRIMARY KEY (TEMPLATE_ID),
    CONSTRAINT UK_PR_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE),
    CONSTRAINT CK_PR_TEMPLATE_STATUS CHECK (STATUS IN ('DRAFT','PUBLISHED','DISABLED'))
);

CREATE TABLE PR_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID  NUMBER(18,0)   NOT NULL,
    TEMPLATE_ID          NUMBER(18,0)   NOT NULL,
    VERSION_NO           NUMBER(10,0)   NOT NULL,
    VERSION_STATUS       VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
    CAPABILITY_FAMILY    VARCHAR2(50)   NOT NULL,
    MERGE_MODE           VARCHAR2(30)   DEFAULT 'SINGLE_WINNER' NOT NULL,
    CHECKSUM             VARCHAR2(100),
    DESCRIPTION          VARCHAR2(1000),
    PUBLISHED_BY         VARCHAR2(50),
    PUBLISHED_AT         DATE,
    CONSTRAINT PK_PR_TEMPLATE_VERSION PRIMARY KEY (TEMPLATE_VERSION_ID),
    CONSTRAINT UK_PR_TEMPLATE_VERSION UNIQUE (TEMPLATE_ID, VERSION_NO),
    CONSTRAINT CK_PR_TV_STATUS CHECK (VERSION_STATUS IN ('DRAFT','PUBLISHED','DISABLED')),
    CONSTRAINT CK_PR_TV_MERGE CHECK (MERGE_MODE IN ('SINGLE_WINNER','MULTI_ALLOWED'))
);

CREATE TABLE PR_TEMPLATE_PARAM_DEF (
    PARAM_DEF_ID         NUMBER(18,0)   NOT NULL,
    TEMPLATE_VERSION_ID  NUMBER(18,0)   NOT NULL,
    PARAM_CODE           VARCHAR2(60)   NOT NULL,
    PARAM_NAME           VARCHAR2(200)  NOT NULL,
    VALUE_TYPE           VARCHAR2(30)   NOT NULL,
    IS_REQUIRED          CHAR(1)        DEFAULT 'N' NOT NULL,
    DEFAULT_TEXT         VARCHAR2(1000),
    DEFAULT_NUMBER       NUMBER(18,4),
    DEFAULT_BOOL         CHAR(1),
    DICT_TYPE            VARCHAR2(50),
    MIN_VALUE            NUMBER(18,4),
    MAX_VALUE            NUMBER(18,4),
    REGEX_RULE           VARCHAR2(500),
    UI_CONTROL           VARCHAR2(50),
    HELP_TEXT            VARCHAR2(1000),
    RISK_FLAG            VARCHAR2(30),
    SORT_NO              NUMBER(10,0)   DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PR_TEMPLATE_PARAM_DEF PRIMARY KEY (PARAM_DEF_ID),
    CONSTRAINT CK_PR_TPD_REQUIRED CHECK (IS_REQUIRED IN ('Y','N'))
);

CREATE TABLE PR_TEMPLATE_STEP_DEF (
    STEP_DEF_ID          NUMBER(18,0)   NOT NULL,
    TEMPLATE_VERSION_ID  NUMBER(18,0)   NOT NULL,
    STEP_NO              NUMBER(10,0)   NOT NULL,
    STEP_KIND            VARCHAR2(20)   NOT NULL,
    CAPABILITY_CODE      VARCHAR2(50)   NOT NULL,
    ACTION_TYPE          VARCHAR2(50),
    EXECUTOR_CODE        VARCHAR2(80),
    ON_ERROR             VARCHAR2(20)   DEFAULT 'STOP' NOT NULL,
    STEP_CONFIG_CLOB     CLOB,
    CONSTRAINT PK_PR_TEMPLATE_STEP_DEF PRIMARY KEY (STEP_DEF_ID),
    CONSTRAINT CK_PR_TSD_ERROR CHECK (ON_ERROR IN ('STOP','SKIP','WARN'))
);

CREATE TABLE PR_TEMPLATE_SCOPE_DEF (
    SCOPE_DEF_ID         NUMBER(18,0)   NOT NULL,
    TEMPLATE_VERSION_ID  NUMBER(18,0)   NOT NULL,
    SCOPE_DIMENSION      VARCHAR2(30)   NOT NULL,
    IS_REQUIRED          CHAR(1)        DEFAULT 'N' NOT NULL,
    ALLOW_MULTIPLE       CHAR(1)        DEFAULT 'N' NOT NULL,
    SORT_NO              NUMBER(10,0)   DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PR_TEMPLATE_SCOPE_DEF PRIMARY KEY (SCOPE_DEF_ID),
    CONSTRAINT CK_PR_TSC_REQUIRED CHECK (IS_REQUIRED IN ('Y','N')),
    CONSTRAINT CK_PR_TSC_MULTI CHECK (ALLOW_MULTIPLE IN ('Y','N'))
);

CREATE INDEX IDX_PR_TEMPLATE_STATUS ON PR_TEMPLATE (STATUS, CURRENT_VERSION_NO);
CREATE INDEX IDX_PR_TEMPLATE_VER_TEMPLATE ON PR_TEMPLATE_VERSION (TEMPLATE_ID, VERSION_STATUS);

-- ============================================================
-- 三、策略模型
-- ============================================================

CREATE TABLE PR_POLICY (
    POLICY_ID            NUMBER(18,0)   NOT NULL,
    POLICY_CODE          VARCHAR2(60)   NOT NULL,
    POLICY_NAME          VARCHAR2(200)  NOT NULL,
    TEMPLATE_ID          NUMBER(18,0)   NOT NULL,
    OWNER_TYPE           VARCHAR2(30)   NOT NULL,
    PUBLISH_PROFILE      VARCHAR2(30)   NOT NULL,
    STATUS               VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
    CURRENT_VERSION_NO   NUMBER(10,0)   DEFAULT 0 NOT NULL,
    CREATED_BY           VARCHAR2(50),
    CREATED_AT           DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY           VARCHAR2(50),
    UPDATED_AT           DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PR_POLICY PRIMARY KEY (POLICY_ID),
    CONSTRAINT UK_PR_POLICY_CODE UNIQUE (POLICY_CODE)
);

CREATE TABLE PR_POLICY_VERSION (
    POLICY_VERSION_ID    NUMBER(18,0)   NOT NULL,
    POLICY_ID            NUMBER(18,0)   NOT NULL,
    TEMPLATE_VERSION_ID  NUMBER(18,0)   NOT NULL,
    VERSION_NO           NUMBER(10,0)   NOT NULL,
    POLICY_STATUS        VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
    EFFECTIVE_FROM       DATE,
    EFFECTIVE_TO         DATE,
    BINDING_TYPE         VARCHAR2(20)   NOT NULL,
    SCOPE_LEVEL          VARCHAR2(30)   NOT NULL,
    PRIORITY_WEIGHT      NUMBER(10,0)   DEFAULT 100 NOT NULL,
    CHECKSUM             VARCHAR2(100),
    LAST_BUILT_PACKAGE_ID NUMBER(18,0),
    CONSTRAINT PK_PR_POLICY_VERSION PRIMARY KEY (POLICY_VERSION_ID),
    CONSTRAINT UK_PR_POLICY_VERSION UNIQUE (POLICY_ID, VERSION_NO),
    CONSTRAINT CK_PR_PV_STATUS CHECK (POLICY_STATUS IN ('DRAFT','VALIDATED','REVIEW_PENDING','APPROVED','PUBLISH_READY','SUPERSEDED'))
);

CREATE TABLE PR_POLICY_BINDING (
    POLICY_BINDING_ID    NUMBER(18,0)   NOT NULL,
    POLICY_VERSION_ID    NUMBER(18,0)   NOT NULL,
    BINDING_TYPE         VARCHAR2(20)   NOT NULL,
    ITEM_CODE            VARCHAR2(50),
    ITEM_NAME            VARCHAR2(200),
    GROUP_CODE           VARCHAR2(50),
    GROUP_NAME           VARCHAR2(200),
    CONSTRAINT PK_PR_POLICY_BINDING PRIMARY KEY (POLICY_BINDING_ID)
);

CREATE TABLE PR_POLICY_SCOPE (
    POLICY_SCOPE_ID      NUMBER(18,0)   NOT NULL,
    POLICY_VERSION_ID    NUMBER(18,0)   NOT NULL,
    SCOPE_DIMENSION      VARCHAR2(30)   NOT NULL,
    SCOPE_OPERATOR       VARCHAR2(20)   NOT NULL,
    SCOPE_VALUE_TEXT     VARCHAR2(1000),
    SCOPE_VALUE_NUMBER   NUMBER(18,4),
    SCOPE_VALUE_DATE     DATE,
    SCOPE_JSON           CLOB,
    CONSTRAINT PK_PR_POLICY_SCOPE PRIMARY KEY (POLICY_SCOPE_ID)
);

CREATE TABLE PR_POLICY_PARAM (
    POLICY_PARAM_ID      NUMBER(18,0)   NOT NULL,
    POLICY_VERSION_ID    NUMBER(18,0)   NOT NULL,
    PARAM_CODE           VARCHAR2(60)   NOT NULL,
    VALUE_TYPE           VARCHAR2(30)   NOT NULL,
    VALUE_TEXT           VARCHAR2(1000),
    VALUE_NUMBER         NUMBER(18,4),
    VALUE_DATE           DATE,
    VALUE_BOOL           CHAR(1),
    EXPR_TEXT            VARCHAR2(2000),
    EXPR_LEVEL           VARCHAR2(20),
    CONSTRAINT PK_PR_POLICY_PARAM PRIMARY KEY (POLICY_PARAM_ID)
);

CREATE TABLE PR_POLICY_REVIEW (
    REVIEW_ID            NUMBER(18,0)   NOT NULL,
    POLICY_VERSION_ID    NUMBER(18,0)   NOT NULL,
    REVIEW_STATUS        VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    REVIEW_STAGE         VARCHAR2(30)   NOT NULL,
    SUBMITTED_BY         VARCHAR2(50),
    SUBMITTED_AT         DATE,
    REVIEWED_BY          VARCHAR2(50),
    REVIEWED_AT          DATE,
    REVIEW_COMMENT       VARCHAR2(1000),
    SOURCE_CHECKSUM      VARCHAR2(100),
    CONSTRAINT PK_PR_POLICY_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT CK_PR_PR_STATUS CHECK (REVIEW_STATUS IN ('PENDING','APPROVED','REJECTED','OUTDATED'))
);

CREATE INDEX IDX_PR_POLICY_TEMPLATE ON PR_POLICY (TEMPLATE_ID, STATUS);
CREATE INDEX IDX_PR_POLICY_VER_STATUS ON PR_POLICY_VERSION (POLICY_STATUS, EFFECTIVE_FROM, EFFECTIVE_TO);
CREATE INDEX IDX_PR_POLICY_BIND_ITEM ON PR_POLICY_BINDING (ITEM_CODE, GROUP_CODE);
CREATE INDEX IDX_PR_POLICY_SCOPE_VER ON PR_POLICY_SCOPE (POLICY_VERSION_ID, SCOPE_DIMENSION);

-- ============================================================
-- 四、运行时模型
-- ============================================================

CREATE TABLE PR_RUNTIME_PACKAGE (
    PACKAGE_ID             NUMBER(18,0)   NOT NULL,
    PACKAGE_VERSION        NUMBER(18,0)   NOT NULL,
    PACKAGE_STATUS         VARCHAR2(20)   DEFAULT 'BUILDING' NOT NULL,
    BUILD_SCOPE            VARCHAR2(20)   DEFAULT 'FULL' NOT NULL,
    SOURCE_CHECKSUM        VARCHAR2(100),
    BUILT_BY               VARCHAR2(50),
    BUILT_AT               DATE,
    ACTIVATED_BY           VARCHAR2(50),
    ACTIVATED_AT           DATE,
    ROLLED_BACK_FROM_PACKAGE_ID NUMBER(18,0),
    CONSTRAINT PK_PR_RUNTIME_PACKAGE PRIMARY KEY (PACKAGE_ID),
    CONSTRAINT UK_PR_RUNTIME_PACKAGE_VER UNIQUE (PACKAGE_VERSION),
    CONSTRAINT CK_PR_RP_STATUS CHECK (PACKAGE_STATUS IN ('BUILDING','BUILT','ACTIVE','SUPERSEDED','BUILD_FAILED'))
);

CREATE TABLE PR_RUNTIME_PACKAGE_POLICY (
    PACKAGE_POLICY_ID      NUMBER(18,0)   NOT NULL,
    PACKAGE_ID             NUMBER(18,0)   NOT NULL,
    POLICY_VERSION_ID      NUMBER(18,0)   NOT NULL,
    POLICY_CODE            VARCHAR2(60)   NOT NULL,
    TEMPLATE_VERSION_ID    NUMBER(18,0)   NOT NULL,
    CAPABILITY_FAMILY      VARCHAR2(50)   NOT NULL,
    PRIORITY_KEY           VARCHAR2(200)  NOT NULL,
    CONSTRAINT PK_PR_RUNTIME_PKG_POLICY PRIMARY KEY (PACKAGE_POLICY_ID)
);

CREATE TABLE PR_RUNTIME_RULE (
    RUNTIME_RULE_ID        NUMBER(18,0)   NOT NULL,
    PACKAGE_ID             NUMBER(18,0)   NOT NULL,
    SOURCE_TEMPLATE_VERSION_ID NUMBER(18,0) NOT NULL,
    SOURCE_POLICY_VERSION_ID   NUMBER(18,0) NOT NULL,
    CAPABILITY_FAMILY      VARCHAR2(50)   NOT NULL,
    MERGE_MODE             VARCHAR2(30)   DEFAULT 'SINGLE_WINNER' NOT NULL,
    TARGET_ITEM_CODE       VARCHAR2(50),
    TARGET_GROUP_CODE      VARCHAR2(50),
    SCOPE_LEVEL            VARCHAR2(30)   NOT NULL,
    PRIORITY_KEY           VARCHAR2(200)  NOT NULL,
    EFFECTIVE_FROM         DATE,
    EFFECTIVE_TO           DATE,
    MATCH_KEY              VARCHAR2(300)  NOT NULL,
    CONSTRAINT PK_PR_RUNTIME_RULE PRIMARY KEY (RUNTIME_RULE_ID),
    CONSTRAINT CK_PR_RR_MERGE CHECK (MERGE_MODE IN ('SINGLE_WINNER','MULTI_ALLOWED'))
);

CREATE TABLE PR_RUNTIME_CONDITION (
    RUNTIME_CONDITION_ID   NUMBER(18,0)   NOT NULL,
    RUNTIME_RULE_ID        NUMBER(18,0)   NOT NULL,
    CONDITION_GROUP        VARCHAR2(50)   DEFAULT 'DEFAULT' NOT NULL,
    CONDITION_TYPE         VARCHAR2(50)   NOT NULL,
    OPERATOR_TYPE          VARCHAR2(20),
    LEFT_KEY               VARCHAR2(100),
    RIGHT_VALUE            VARCHAR2(1000),
    PARAMS_JSON            CLOB,
    SORT_NO                NUMBER(10,0)   DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PR_RUNTIME_CONDITION PRIMARY KEY (RUNTIME_CONDITION_ID)
);

CREATE TABLE PR_RUNTIME_ACTION (
    RUNTIME_ACTION_ID      NUMBER(18,0)   NOT NULL,
    RUNTIME_RULE_ID        NUMBER(18,0)   NOT NULL,
    STEP_NO                NUMBER(10,0)   NOT NULL,
    ACTION_TYPE            VARCHAR2(50)   NOT NULL,
    EXECUTOR_CODE          VARCHAR2(80)   NOT NULL,
    PARAMS_JSON            CLOB,
    EXCLUSIVE_GROUP        VARCHAR2(50),
    SORT_NO                NUMBER(10,0)   DEFAULT 0 NOT NULL,
    ON_ERROR               VARCHAR2(20)   DEFAULT 'STOP' NOT NULL,
    CONSTRAINT PK_PR_RUNTIME_ACTION PRIMARY KEY (RUNTIME_ACTION_ID),
    CONSTRAINT CK_PR_RA2_ERROR CHECK (ON_ERROR IN ('STOP','SKIP','WARN'))
);

CREATE TABLE PR_RUNTIME_PACKAGE_STATE (
    STATE_CODE             VARCHAR2(20)   NOT NULL,
    ACTIVE_PACKAGE_ID      NUMBER(18,0)   DEFAULT 0 NOT NULL,
    ACTIVE_PACKAGE_VERSION NUMBER(18,0)   DEFAULT 0 NOT NULL,
    UPDATED_AT             DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY             VARCHAR2(50),
    CONSTRAINT PK_PR_RUNTIME_PACKAGE_STATE PRIMARY KEY (STATE_CODE)
);

INSERT INTO PR_RUNTIME_PACKAGE_STATE (
    STATE_CODE,
    ACTIVE_PACKAGE_ID,
    ACTIVE_PACKAGE_VERSION,
    UPDATED_AT,
    UPDATED_BY
) VALUES (
    'ACTIVE',
    0,
    0,
    SYSDATE,
    'INIT'
);

CREATE INDEX IDX_PR_RPP_PACKAGE ON PR_RUNTIME_PACKAGE_POLICY (PACKAGE_ID, POLICY_VERSION_ID);
CREATE INDEX IDX_PR_RR_PACKAGE_ITEM ON PR_RUNTIME_RULE (PACKAGE_ID, TARGET_ITEM_CODE, EFFECTIVE_FROM, EFFECTIVE_TO);
CREATE INDEX IDX_PR_RR_PACKAGE_GROUP ON PR_RUNTIME_RULE (PACKAGE_ID, TARGET_GROUP_CODE, EFFECTIVE_FROM, EFFECTIVE_TO);
CREATE INDEX IDX_PR_RR_MATCH_KEY ON PR_RUNTIME_RULE (MATCH_KEY, CAPABILITY_FAMILY);
CREATE INDEX IDX_PR_RC2_RULE ON PR_RUNTIME_CONDITION (RUNTIME_RULE_ID, CONDITION_GROUP, SORT_NO);
CREATE INDEX IDX_PR_RA2_RULE ON PR_RUNTIME_ACTION (RUNTIME_RULE_ID, SORT_NO);

-- ============================================================
-- 五、追溯链补充字段
-- ============================================================

ALTER TABLE PR_CHARGE_REQUEST_LOG ADD (
    RUNTIME_PACKAGE_ID       NUMBER(18,0),
    RUNTIME_PACKAGE_VERSION  NUMBER(18,0)
);

ALTER TABLE PR_CHARGE_TRACE_STEP ADD (
    RUNTIME_PACKAGE_ID         NUMBER(18,0),
    RUNTIME_RULE_ID            NUMBER(18,0),
    SOURCE_POLICY_VERSION_ID   NUMBER(18,0),
    SOURCE_TEMPLATE_VERSION_ID NUMBER(18,0)
);

ALTER TABLE PR_CHARGE_DISCOUNT_DETAIL ADD (
    RUNTIME_PACKAGE_ID         NUMBER(18,0),
    RUNTIME_RULE_ID            NUMBER(18,0),
    SOURCE_POLICY_VERSION_ID   NUMBER(18,0),
    SOURCE_TEMPLATE_VERSION_ID NUMBER(18,0)
);

CREATE INDEX IDX_PR_CRL_RUNTIME_PKG ON PR_CHARGE_REQUEST_LOG (RUNTIME_PACKAGE_ID, RUNTIME_PACKAGE_VERSION);
CREATE INDEX IDX_PR_CTS_RUNTIME_PKG ON PR_CHARGE_TRACE_STEP (RUNTIME_PACKAGE_ID, RUNTIME_RULE_ID);
CREATE INDEX IDX_PR_CDD_RUNTIME_PKG ON PR_CHARGE_DISCOUNT_DETAIL (RUNTIME_PACKAGE_ID, RUNTIME_RULE_ID);
