-- ============================================================
-- 配置优先规则平台 - 第一批模板目录初始化
-- 说明：
--   1. 仅初始化第一批高频模板族。
--   2. 模板参数采用 LEGACY_ACTION_PARAMS_JSON 透传旧动作 ParamsJson，
--      便于历史规则导入后先形成可编译草稿，再逐步精细化参数拆解。
-- ============================================================

-- TPL_INCREMENT_PERCENT
INSERT INTO PR_TEMPLATE (
    TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME, CATEGORY, RISK_LEVEL, EXPRESSION_MODE,
    STATUS, CURRENT_VERSION_NO, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_PR_TEMPLATE.NEXTVAL, 'TPL_INCREMENT_PERCENT', '固定比例递增', 'FORMULA', 'LOW', 'WEAK',
    'PUBLISHED', 1, 'SEED', SYSDATE, 'SEED', SYSDATE
);

INSERT INTO PR_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID, TEMPLATE_ID, VERSION_NO, VERSION_STATUS,
    CAPABILITY_FAMILY, MERGE_MODE, CHECKSUM, DESCRIPTION, PUBLISHED_BY, PUBLISHED_AT
)
SELECT
    SEQ_PR_TEMPLATE_VERSION.NEXTVAL,
    TEMPLATE_ID,
    1,
    'PUBLISHED',
    'FORMULA_PRICING',
    'SINGLE_WINNER',
    'TPL_INCREMENT_PERCENT_V1',
    '固定比例递增导入模板',
    'SEED',
    SYSDATE
FROM PR_TEMPLATE
WHERE TEMPLATE_CODE = 'TPL_INCREMENT_PERCENT';

INSERT INTO PR_TEMPLATE_PARAM_DEF (
    PARAM_DEF_ID, TEMPLATE_VERSION_ID, PARAM_CODE, PARAM_NAME, VALUE_TYPE, IS_REQUIRED,
    HELP_TEXT, SORT_NO
)
SELECT
    SEQ_PR_TEMPLATE_PARAM_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    'LEGACY_ACTION_PARAMS_JSON',
    '历史动作参数',
    'TEXT',
    'Y',
    '透传旧 PR_RULE_ACTION.PARAMS_JSON',
    1
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_INCREMENT_PERCENT_V1';

INSERT INTO PR_TEMPLATE_STEP_DEF (
    STEP_DEF_ID, TEMPLATE_VERSION_ID, STEP_NO, STEP_KIND, CAPABILITY_CODE,
    ACTION_TYPE, EXECUTOR_CODE, ON_ERROR
)
SELECT
    SEQ_PR_TEMPLATE_STEP_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    10,
    'ACTION',
    'FORMULA_PRICING',
    'FORMULA_CALC',
    'INCREMENT_PERCENT',
    'STOP'
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_INCREMENT_PERCENT_V1';

INSERT INTO PR_TEMPLATE_SCOPE_DEF (
    SCOPE_DEF_ID, TEMPLATE_VERSION_ID, SCOPE_DIMENSION, IS_REQUIRED, ALLOW_MULTIPLE, SORT_NO
)
SELECT SEQ_PR_TEMPLATE_SCOPE_DEF.NEXTVAL, TEMPLATE_VERSION_ID, 'SCENE', 'N', 'N', 1
FROM PR_TEMPLATE_VERSION WHERE CHECKSUM = 'TPL_INCREMENT_PERCENT_V1';

INSERT INTO PR_TEMPLATE_SCOPE_DEF (
    SCOPE_DEF_ID, TEMPLATE_VERSION_ID, SCOPE_DIMENSION, IS_REQUIRED, ALLOW_MULTIPLE, SORT_NO
)
SELECT SEQ_PR_TEMPLATE_SCOPE_DEF.NEXTVAL, TEMPLATE_VERSION_ID, 'BODY_PART', 'N', 'N', 2
FROM PR_TEMPLATE_VERSION WHERE CHECKSUM = 'TPL_INCREMENT_PERCENT_V1';

-- TPL_AREA_STEP_INCREMENT
INSERT INTO PR_TEMPLATE (
    TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME, CATEGORY, RISK_LEVEL, EXPRESSION_MODE,
    STATUS, CURRENT_VERSION_NO, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_PR_TEMPLATE.NEXTVAL, 'TPL_AREA_STEP_INCREMENT', '面积分段递增', 'FORMULA', 'LOW', 'WEAK',
    'PUBLISHED', 1, 'SEED', SYSDATE, 'SEED', SYSDATE
);

INSERT INTO PR_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID, TEMPLATE_ID, VERSION_NO, VERSION_STATUS,
    CAPABILITY_FAMILY, MERGE_MODE, CHECKSUM, DESCRIPTION, PUBLISHED_BY, PUBLISHED_AT
)
SELECT
    SEQ_PR_TEMPLATE_VERSION.NEXTVAL,
    TEMPLATE_ID,
    1,
    'PUBLISHED',
    'FORMULA_PRICING',
    'SINGLE_WINNER',
    'TPL_AREA_STEP_INCREMENT_V1',
    '面积分段递增导入模板',
    'SEED',
    SYSDATE
FROM PR_TEMPLATE
WHERE TEMPLATE_CODE = 'TPL_AREA_STEP_INCREMENT';

INSERT INTO PR_TEMPLATE_PARAM_DEF (
    PARAM_DEF_ID, TEMPLATE_VERSION_ID, PARAM_CODE, PARAM_NAME, VALUE_TYPE, IS_REQUIRED,
    HELP_TEXT, SORT_NO
)
SELECT
    SEQ_PR_TEMPLATE_PARAM_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    'LEGACY_ACTION_PARAMS_JSON',
    '历史动作参数',
    'TEXT',
    'Y',
    '透传旧 PR_RULE_ACTION.PARAMS_JSON',
    1
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_AREA_STEP_INCREMENT_V1';

INSERT INTO PR_TEMPLATE_STEP_DEF (
    STEP_DEF_ID, TEMPLATE_VERSION_ID, STEP_NO, STEP_KIND, CAPABILITY_CODE,
    ACTION_TYPE, EXECUTOR_CODE, ON_ERROR
)
SELECT
    SEQ_PR_TEMPLATE_STEP_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    10,
    'ACTION',
    'FORMULA_PRICING',
    'FORMULA_CALC',
    'AREA_STEP_INCREMENT',
    'STOP'
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_AREA_STEP_INCREMENT_V1';

INSERT INTO PR_TEMPLATE_SCOPE_DEF (
    SCOPE_DEF_ID, TEMPLATE_VERSION_ID, SCOPE_DIMENSION, IS_REQUIRED, ALLOW_MULTIPLE, SORT_NO
)
SELECT SEQ_PR_TEMPLATE_SCOPE_DEF.NEXTVAL, TEMPLATE_VERSION_ID, 'SCENE', 'N', 'N', 1
FROM PR_TEMPLATE_VERSION WHERE CHECKSUM = 'TPL_AREA_STEP_INCREMENT_V1';

-- TPL_TIME_WINDOW_QTY_LIMIT
INSERT INTO PR_TEMPLATE (
    TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME, CATEGORY, RISK_LEVEL, EXPRESSION_MODE,
    STATUS, CURRENT_VERSION_NO, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_PR_TEMPLATE.NEXTVAL, 'TPL_TIME_WINDOW_QTY_LIMIT', '时间窗数量限制', 'LIMIT', 'LOW', 'WEAK',
    'PUBLISHED', 1, 'SEED', SYSDATE, 'SEED', SYSDATE
);

INSERT INTO PR_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID, TEMPLATE_ID, VERSION_NO, VERSION_STATUS,
    CAPABILITY_FAMILY, MERGE_MODE, CHECKSUM, DESCRIPTION, PUBLISHED_BY, PUBLISHED_AT
)
SELECT
    SEQ_PR_TEMPLATE_VERSION.NEXTVAL,
    TEMPLATE_ID,
    1,
    'PUBLISHED',
    'QTY_LIMIT_TIME_WINDOW',
    'SINGLE_WINNER',
    'TPL_TIME_WINDOW_QTY_LIMIT_V1',
    '2 小时窗口数量限制导入模板',
    'SEED',
    SYSDATE
FROM PR_TEMPLATE
WHERE TEMPLATE_CODE = 'TPL_TIME_WINDOW_QTY_LIMIT';

INSERT INTO PR_TEMPLATE_PARAM_DEF (
    PARAM_DEF_ID, TEMPLATE_VERSION_ID, PARAM_CODE, PARAM_NAME, VALUE_TYPE, IS_REQUIRED,
    HELP_TEXT, SORT_NO
)
SELECT
    SEQ_PR_TEMPLATE_PARAM_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    'LEGACY_ACTION_PARAMS_JSON',
    '历史动作参数',
    'TEXT',
    'Y',
    '透传旧 PR_RULE_ACTION.PARAMS_JSON',
    1
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_TIME_WINDOW_QTY_LIMIT_V1';

INSERT INTO PR_TEMPLATE_STEP_DEF (
    STEP_DEF_ID, TEMPLATE_VERSION_ID, STEP_NO, STEP_KIND, CAPABILITY_CODE,
    ACTION_TYPE, EXECUTOR_CODE, ON_ERROR
)
SELECT
    SEQ_PR_TEMPLATE_STEP_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    10,
    'ACTION',
    'QTY_LIMIT_TIME_WINDOW',
    'APPLY_TIME_WINDOW_LIMIT',
    'TimeWindowLimitExecutor',
    'STOP'
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_TIME_WINDOW_QTY_LIMIT_V1';

INSERT INTO PR_TEMPLATE_SCOPE_DEF (
    SCOPE_DEF_ID, TEMPLATE_VERSION_ID, SCOPE_DIMENSION, IS_REQUIRED, ALLOW_MULTIPLE, SORT_NO
)
SELECT SEQ_PR_TEMPLATE_SCOPE_DEF.NEXTVAL, TEMPLATE_VERSION_ID, 'SCENE', 'N', 'N', 1
FROM PR_TEMPLATE_VERSION WHERE CHECKSUM = 'TPL_TIME_WINDOW_QTY_LIMIT_V1';

-- TPL_DAILY_QTY_LIMIT
INSERT INTO PR_TEMPLATE (
    TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME, CATEGORY, RISK_LEVEL, EXPRESSION_MODE,
    STATUS, CURRENT_VERSION_NO, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_PR_TEMPLATE.NEXTVAL, 'TPL_DAILY_QTY_LIMIT', '单日数量限制', 'LIMIT', 'LOW', 'WEAK',
    'PUBLISHED', 1, 'SEED', SYSDATE, 'SEED', SYSDATE
);

INSERT INTO PR_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID, TEMPLATE_ID, VERSION_NO, VERSION_STATUS,
    CAPABILITY_FAMILY, MERGE_MODE, CHECKSUM, DESCRIPTION, PUBLISHED_BY, PUBLISHED_AT
)
SELECT
    SEQ_PR_TEMPLATE_VERSION.NEXTVAL,
    TEMPLATE_ID,
    1,
    'PUBLISHED',
    'QTY_LIMIT_DAILY',
    'SINGLE_WINNER',
    'TPL_DAILY_QTY_LIMIT_V1',
    '单日数量限制导入模板',
    'SEED',
    SYSDATE
FROM PR_TEMPLATE
WHERE TEMPLATE_CODE = 'TPL_DAILY_QTY_LIMIT';

INSERT INTO PR_TEMPLATE_PARAM_DEF (
    PARAM_DEF_ID, TEMPLATE_VERSION_ID, PARAM_CODE, PARAM_NAME, VALUE_TYPE, IS_REQUIRED,
    HELP_TEXT, SORT_NO
)
SELECT
    SEQ_PR_TEMPLATE_PARAM_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    'LEGACY_ACTION_PARAMS_JSON',
    '历史动作参数',
    'TEXT',
    'Y',
    '透传旧 PR_RULE_ACTION.PARAMS_JSON',
    1
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_DAILY_QTY_LIMIT_V1';

INSERT INTO PR_TEMPLATE_STEP_DEF (
    STEP_DEF_ID, TEMPLATE_VERSION_ID, STEP_NO, STEP_KIND, CAPABILITY_CODE,
    ACTION_TYPE, EXECUTOR_CODE, ON_ERROR
)
SELECT
    SEQ_PR_TEMPLATE_STEP_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    10,
    'ACTION',
    'QTY_LIMIT_DAILY',
    'APPLY_DAY_LIMIT_QTY',
    'DailyQtyLimitExecutor',
    'STOP'
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_DAILY_QTY_LIMIT_V1';

-- TPL_ONCE_QTY_LIMIT
INSERT INTO PR_TEMPLATE (
    TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME, CATEGORY, RISK_LEVEL, EXPRESSION_MODE,
    STATUS, CURRENT_VERSION_NO, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_PR_TEMPLATE.NEXTVAL, 'TPL_ONCE_QTY_LIMIT', '单次数量限制', 'LIMIT', 'LOW', 'WEAK',
    'PUBLISHED', 1, 'SEED', SYSDATE, 'SEED', SYSDATE
);

INSERT INTO PR_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID, TEMPLATE_ID, VERSION_NO, VERSION_STATUS,
    CAPABILITY_FAMILY, MERGE_MODE, CHECKSUM, DESCRIPTION, PUBLISHED_BY, PUBLISHED_AT
)
SELECT
    SEQ_PR_TEMPLATE_VERSION.NEXTVAL,
    TEMPLATE_ID,
    1,
    'PUBLISHED',
    'QTY_LIMIT_ONCE',
    'SINGLE_WINNER',
    'TPL_ONCE_QTY_LIMIT_V1',
    '单次数量限制导入模板',
    'SEED',
    SYSDATE
FROM PR_TEMPLATE
WHERE TEMPLATE_CODE = 'TPL_ONCE_QTY_LIMIT';

INSERT INTO PR_TEMPLATE_PARAM_DEF (
    PARAM_DEF_ID, TEMPLATE_VERSION_ID, PARAM_CODE, PARAM_NAME, VALUE_TYPE, IS_REQUIRED,
    HELP_TEXT, SORT_NO
)
SELECT
    SEQ_PR_TEMPLATE_PARAM_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    'LEGACY_ACTION_PARAMS_JSON',
    '历史动作参数',
    'TEXT',
    'Y',
    '透传旧 PR_RULE_ACTION.PARAMS_JSON',
    1
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_ONCE_QTY_LIMIT_V1';

INSERT INTO PR_TEMPLATE_STEP_DEF (
    STEP_DEF_ID, TEMPLATE_VERSION_ID, STEP_NO, STEP_KIND, CAPABILITY_CODE,
    ACTION_TYPE, EXECUTOR_CODE, ON_ERROR
)
SELECT
    SEQ_PR_TEMPLATE_STEP_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    10,
    'ACTION',
    'QTY_LIMIT_ONCE',
    'APPLY_ONCE_LIMIT_QTY',
    'OnceQtyLimitExecutor',
    'STOP'
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_ONCE_QTY_LIMIT_V1';

-- TPL_UNIT_CONVERT_BY_BODY_PART
INSERT INTO PR_TEMPLATE (
    TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME, CATEGORY, RISK_LEVEL, EXPRESSION_MODE,
    STATUS, CURRENT_VERSION_NO, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    SEQ_PR_TEMPLATE.NEXTVAL, 'TPL_UNIT_CONVERT_BY_BODY_PART', '按部位数量换算', 'CONVERT', 'LOW', 'WEAK',
    'PUBLISHED', 1, 'SEED', SYSDATE, 'SEED', SYSDATE
);

INSERT INTO PR_TEMPLATE_VERSION (
    TEMPLATE_VERSION_ID, TEMPLATE_ID, VERSION_NO, VERSION_STATUS,
    CAPABILITY_FAMILY, MERGE_MODE, CHECKSUM, DESCRIPTION, PUBLISHED_BY, PUBLISHED_AT
)
SELECT
    SEQ_PR_TEMPLATE_VERSION.NEXTVAL,
    TEMPLATE_ID,
    1,
    'PUBLISHED',
    'UNIT_CONVERSION',
    'SINGLE_WINNER',
    'TPL_UNIT_CONVERT_BY_BODY_PART_V1',
    '按部位数量换算导入模板',
    'SEED',
    SYSDATE
FROM PR_TEMPLATE
WHERE TEMPLATE_CODE = 'TPL_UNIT_CONVERT_BY_BODY_PART';

INSERT INTO PR_TEMPLATE_PARAM_DEF (
    PARAM_DEF_ID, TEMPLATE_VERSION_ID, PARAM_CODE, PARAM_NAME, VALUE_TYPE, IS_REQUIRED,
    HELP_TEXT, SORT_NO
)
SELECT
    SEQ_PR_TEMPLATE_PARAM_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    'LEGACY_ACTION_PARAMS_JSON',
    '历史动作参数',
    'TEXT',
    'Y',
    '透传旧 PR_RULE_ACTION.PARAMS_JSON',
    1
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_UNIT_CONVERT_BY_BODY_PART_V1';

INSERT INTO PR_TEMPLATE_STEP_DEF (
    STEP_DEF_ID, TEMPLATE_VERSION_ID, STEP_NO, STEP_KIND, CAPABILITY_CODE,
    ACTION_TYPE, EXECUTOR_CODE, ON_ERROR
)
SELECT
    SEQ_PR_TEMPLATE_STEP_DEF.NEXTVAL,
    TEMPLATE_VERSION_ID,
    10,
    'ACTION',
    'UNIT_CONVERSION',
    'CONVERT_QTY',
    'UnitConvertExecutor',
    'STOP'
FROM PR_TEMPLATE_VERSION
WHERE CHECKSUM = 'TPL_UNIT_CONVERT_BY_BODY_PART_V1';

INSERT INTO PR_TEMPLATE_SCOPE_DEF (
    SCOPE_DEF_ID, TEMPLATE_VERSION_ID, SCOPE_DIMENSION, IS_REQUIRED, ALLOW_MULTIPLE, SORT_NO
)
SELECT SEQ_PR_TEMPLATE_SCOPE_DEF.NEXTVAL, TEMPLATE_VERSION_ID, 'BODY_PART', 'N', 'N', 1
FROM PR_TEMPLATE_VERSION WHERE CHECKSUM = 'TPL_UNIT_CONVERT_BY_BODY_PART_V1';
