-- ============================================================
-- 配置优先规则平台 - 历史规则首批导入 SQL
-- 说明：
--   1. 本脚本把旧 PR_RULE_* 中已发布的受支持动作导入为新策略草稿。
--   2. 导入粒度为“旧规则 + 单个受支持动作” -> “一条新策略”。
--   3. 动作参数先透传到 LEGACY_ACTION_PARAMS_JSON，后续可在工作台中逐步精细化。
-- ============================================================

-- 1. 导入策略主表
INSERT INTO PR_POLICY (
    POLICY_ID, POLICY_CODE, POLICY_NAME, TEMPLATE_ID, OWNER_TYPE, PUBLISH_PROFILE,
    STATUS, CURRENT_VERSION_NO, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT
    SEQ_PR_POLICY.NEXTVAL,
    ('IMP_' || H.RULE_CODE || '_' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE)),
    (H.RULE_NAME || '-' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE) || '-导入草稿'),
    T.TEMPLATE_ID,
    'MIGRATION',
    'REVIEW_REQUIRED',
    'DRAFT',
    1,
    'SQL_IMPORT',
    SYSDATE,
    'SQL_IMPORT',
    SYSDATE
FROM PR_RULE_HEADER H
JOIN PR_RULE_ACTION A
  ON A.RULE_ID = H.RULE_ID
 AND A.VERSION_NO = H.CURRENT_VERSION
 AND A.IS_ENABLED = 'Y'
JOIN PR_TEMPLATE T
  ON T.TEMPLATE_CODE = CASE
       WHEN A.ACTION_TYPE = 'FORMULA_CALC' AND A.EXECUTOR_CODE = 'INCREMENT_PERCENT' THEN 'TPL_INCREMENT_PERCENT'
       WHEN A.ACTION_TYPE = 'FORMULA_CALC' AND A.EXECUTOR_CODE = 'AREA_STEP_INCREMENT' THEN 'TPL_AREA_STEP_INCREMENT'
       WHEN A.ACTION_TYPE = 'APPLY_TIME_WINDOW_LIMIT' THEN 'TPL_TIME_WINDOW_QTY_LIMIT'
       WHEN A.ACTION_TYPE = 'APPLY_DAY_LIMIT_QTY' THEN 'TPL_DAILY_QTY_LIMIT'
       WHEN A.ACTION_TYPE = 'APPLY_ONCE_LIMIT_QTY' THEN 'TPL_ONCE_QTY_LIMIT'
       WHEN A.ACTION_TYPE = 'CONVERT_QTY' THEN 'TPL_UNIT_CONVERT_BY_BODY_PART'
     END
LEFT JOIN PR_POLICY P
  ON P.POLICY_CODE = ('IMP_' || H.RULE_CODE || '_' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE))
WHERE H.STATUS = 'PUBLISHED'
  AND H.IS_ENABLED = 'Y'
  AND P.POLICY_ID IS NULL;

-- 2. 导入策略版本
INSERT INTO PR_POLICY_VERSION (
    POLICY_VERSION_ID, POLICY_ID, TEMPLATE_VERSION_ID, VERSION_NO, POLICY_STATUS,
    EFFECTIVE_FROM, EFFECTIVE_TO, BINDING_TYPE, SCOPE_LEVEL, PRIORITY_WEIGHT,
    CHECKSUM, LAST_BUILT_PACKAGE_ID
)
SELECT
    SEQ_PR_POLICY_VERSION.NEXTVAL,
    P.POLICY_ID,
    TV.TEMPLATE_VERSION_ID,
    1,
    'DRAFT',
    H.EFFECTIVE_FROM,
    H.EFFECTIVE_TO,
    CASE
      WHEN H.ITEM_CODE IS NOT NULL THEN 'ITEM'
      WHEN H.GROUP_CODE IS NOT NULL THEN 'GROUP'
      ELSE 'GLOBAL'
    END,
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM PR_RULE_CONDITION C
        WHERE C.RULE_ID = H.RULE_ID
          AND C.VERSION_NO = H.CURRENT_VERSION
          AND C.IS_ENABLED = 'Y'
          AND C.CONDITION_TYPE IN ('CHARGE_SCENE', 'CHARGE_SCENE_MATCH')
      ) THEN 'SCENE'
      ELSE 'HOSPITAL'
    END,
    H.PRIORITY,
    ('IMP-' || H.RULE_CODE || '-' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE)),
    NULL
FROM PR_RULE_HEADER H
JOIN PR_RULE_ACTION A
  ON A.RULE_ID = H.RULE_ID
 AND A.VERSION_NO = H.CURRENT_VERSION
 AND A.IS_ENABLED = 'Y'
JOIN PR_POLICY P
  ON P.POLICY_CODE = ('IMP_' || H.RULE_CODE || '_' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE))
JOIN PR_TEMPLATE T
  ON T.TEMPLATE_ID = P.TEMPLATE_ID
JOIN PR_TEMPLATE_VERSION TV
  ON TV.TEMPLATE_ID = T.TEMPLATE_ID
 AND TV.VERSION_NO = 1
LEFT JOIN PR_POLICY_VERSION PV
  ON PV.POLICY_ID = P.POLICY_ID
 AND PV.VERSION_NO = 1
WHERE PV.POLICY_VERSION_ID IS NULL;

-- 3. 导入绑定对象
INSERT INTO PR_POLICY_BINDING (
    POLICY_BINDING_ID, POLICY_VERSION_ID, BINDING_TYPE, ITEM_CODE, ITEM_NAME, GROUP_CODE, GROUP_NAME
)
SELECT
    SEQ_PR_POLICY_BINDING.NEXTVAL,
    PV.POLICY_VERSION_ID,
    PV.BINDING_TYPE,
    H.ITEM_CODE,
    H.ITEM_NAME,
    H.GROUP_CODE,
    NULL
FROM PR_RULE_HEADER H
JOIN PR_RULE_ACTION A
  ON A.RULE_ID = H.RULE_ID
 AND A.VERSION_NO = H.CURRENT_VERSION
 AND A.IS_ENABLED = 'Y'
JOIN PR_POLICY P
  ON P.POLICY_CODE = ('IMP_' || H.RULE_CODE || '_' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE))
JOIN PR_POLICY_VERSION PV
  ON PV.POLICY_ID = P.POLICY_ID
LEFT JOIN PR_POLICY_BINDING PB
  ON PB.POLICY_VERSION_ID = PV.POLICY_VERSION_ID
WHERE PB.POLICY_BINDING_ID IS NULL;

-- 4. 导入作用域（仅首批支持的条件维度）
INSERT INTO PR_POLICY_SCOPE (
    POLICY_SCOPE_ID, POLICY_VERSION_ID, SCOPE_DIMENSION, SCOPE_OPERATOR,
    SCOPE_VALUE_TEXT, SCOPE_VALUE_NUMBER, SCOPE_VALUE_DATE, SCOPE_JSON
)
SELECT
    SEQ_PR_POLICY_SCOPE.NEXTVAL,
    PV.POLICY_VERSION_ID,
    CASE
      WHEN C.CONDITION_TYPE IN ('CHARGE_SCENE', 'CHARGE_SCENE_MATCH') THEN 'SCENE'
      WHEN C.CONDITION_TYPE IN ('BODY_PART', 'BODY_PART_MATCH') THEN 'BODY_PART'
      WHEN C.CONDITION_TYPE = 'VISIT_TYPE_MATCH' THEN 'VISIT_TYPE'
      WHEN C.CONDITION_TYPE = 'TIME_RANGE' THEN 'TIME_RANGE'
    END,
    NVL(C.OPERATOR_TYPE, 'EQ'),
    C.RIGHT_VALUE,
    NULL,
    NULL,
    C.PARAMS_JSON
FROM PR_RULE_HEADER H
JOIN PR_RULE_ACTION A
  ON A.RULE_ID = H.RULE_ID
 AND A.VERSION_NO = H.CURRENT_VERSION
 AND A.IS_ENABLED = 'Y'
JOIN PR_POLICY P
  ON P.POLICY_CODE = ('IMP_' || H.RULE_CODE || '_' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE))
JOIN PR_POLICY_VERSION PV
  ON PV.POLICY_ID = P.POLICY_ID
JOIN PR_RULE_CONDITION C
  ON C.RULE_ID = H.RULE_ID
 AND C.VERSION_NO = H.CURRENT_VERSION
 AND C.IS_ENABLED = 'Y'
LEFT JOIN PR_POLICY_SCOPE PS
  ON PS.POLICY_VERSION_ID = PV.POLICY_VERSION_ID
 AND PS.SCOPE_DIMENSION = CASE
       WHEN C.CONDITION_TYPE IN ('CHARGE_SCENE', 'CHARGE_SCENE_MATCH') THEN 'SCENE'
       WHEN C.CONDITION_TYPE IN ('BODY_PART', 'BODY_PART_MATCH') THEN 'BODY_PART'
       WHEN C.CONDITION_TYPE = 'VISIT_TYPE_MATCH' THEN 'VISIT_TYPE'
       WHEN C.CONDITION_TYPE = 'TIME_RANGE' THEN 'TIME_RANGE'
     END
 AND NVL(PS.SCOPE_VALUE_TEXT, '~') = NVL(C.RIGHT_VALUE, '~')
WHERE C.CONDITION_TYPE IN ('CHARGE_SCENE', 'CHARGE_SCENE_MATCH', 'BODY_PART', 'BODY_PART_MATCH', 'VISIT_TYPE_MATCH', 'TIME_RANGE')
  AND PS.POLICY_SCOPE_ID IS NULL;

-- 5. 导入动作参数透传
INSERT INTO PR_POLICY_PARAM (
    POLICY_PARAM_ID, POLICY_VERSION_ID, PARAM_CODE, VALUE_TYPE, VALUE_TEXT,
    VALUE_NUMBER, VALUE_DATE, VALUE_BOOL, EXPR_TEXT, EXPR_LEVEL
)
SELECT
    SEQ_PR_POLICY_PARAM.NEXTVAL,
    PV.POLICY_VERSION_ID,
    'LEGACY_ACTION_PARAMS_JSON',
    'TEXT',
    A.PARAMS_JSON,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
FROM PR_RULE_HEADER H
JOIN PR_RULE_ACTION A
  ON A.RULE_ID = H.RULE_ID
 AND A.VERSION_NO = H.CURRENT_VERSION
 AND A.IS_ENABLED = 'Y'
JOIN PR_POLICY P
  ON P.POLICY_CODE = ('IMP_' || H.RULE_CODE || '_' || NVL(A.EXECUTOR_CODE, A.ACTION_TYPE))
JOIN PR_POLICY_VERSION PV
  ON PV.POLICY_ID = P.POLICY_ID
LEFT JOIN PR_POLICY_PARAM PP
  ON PP.POLICY_VERSION_ID = PV.POLICY_VERSION_ID
 AND PP.PARAM_CODE = 'LEGACY_ACTION_PARAMS_JSON'
WHERE A.PARAMS_JSON IS NOT NULL
  AND PP.POLICY_PARAM_ID IS NULL;
