-- Oracle 并发与事务基础结构验证脚本
-- 只读检查脚本：不插入、不更新、不删除业务数据。
-- 执行环境：预发 Oracle 11g。

PROMPT === 1. 唯一索引检查 ===

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE INDEX_NAME IN (
  'UK_PR_CRL_BIZ',
  'UK_PR_CRV_NO',
  'UK_PR_RAP_PENDING',
  'UK_PR_RV_RULE_VER',
  'UK_PR_RULE_HEADER_CODE',
  'UK_PR_DICT_TYPE_CODE'
)
ORDER BY TABLE_NAME, INDEX_NAME;

PROMPT === 2. 关键锁表和占用表结构检查 ===

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN ('PR_LIMIT_LOCK', 'PR_LIMIT_OCCUPY')
AND COLUMN_NAME IN (
  'LOCK_KEY',
  'LIMIT_KEY',
  'LIMIT_DIMENSION_CODE',
  'BUSINESS_CHARGE_TIME',
  'STATUS',
  'EXPIRE_AT',
  'OCCUPY_TYPE',
  'ORIGINAL_OCCUPY_ID'
)
ORDER BY TABLE_NAME, COLUMN_ID;

PROMPT === 3. 限额占用索引检查 ===

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME = 'PR_LIMIT_OCCUPY'
ORDER BY INDEX_NAME;

PROMPT === 4. confirm 幂等重复业务键检查 ===

SELECT SOURCE_SYSTEM, BUSINESS_REQUEST_NO, CALL_TYPE, COUNT(*) AS CNT
FROM PR_CHARGE_REQUEST_LOG
WHERE CALL_TYPE = 'CONFIRM'
AND BUSINESS_REQUEST_NO IS NOT NULL
GROUP BY SOURCE_SYSTEM, BUSINESS_REQUEST_NO, CALL_TYPE
HAVING COUNT(*) > 1;

PROMPT === 5. reverse 幂等重复业务键检查 ===

SELECT ORIGINAL_REQUEST_ID, REVERSE_NO, COUNT(*) AS CNT
FROM PR_CHARGE_REVERSE_LOG
WHERE REVERSE_NO IS NOT NULL
GROUP BY ORIGINAL_REQUEST_ID, REVERSE_NO
HAVING COUNT(*) > 1;

PROMPT === 6. 重复 pending 审批检查 ===

SELECT RULE_ID, VERSION_NO, ACTION_TYPE, COUNT(*) AS CNT
FROM PR_RULE_APPROVAL
WHERE APPROVAL_STATUS = 'PENDING'
GROUP BY RULE_ID, VERSION_NO, ACTION_TYPE
HAVING COUNT(*) > 1;

PROMPT === 7. pending 超时请求检查 ===

SELECT REQUEST_ID, SOURCE_SYSTEM, BUSINESS_REQUEST_NO, REQUEST_AT, BUSINESS_STATUS
FROM PR_CHARGE_REQUEST_LOG
WHERE BUSINESS_STATUS = 'CONFIRM_PENDING'
AND REQUEST_AT < SYSDATE - (30 / 1440)
ORDER BY REQUEST_AT;

PROMPT === 8. 请求日志与限额占用状态不一致检查 ===

SELECT r.REQUEST_ID,
       r.BUSINESS_REQUEST_NO,
       r.BUSINESS_STATUS,
       o.STATUS AS OCCUPY_STATUS,
       COUNT(*) AS CNT
FROM PR_CHARGE_REQUEST_LOG r
JOIN PR_LIMIT_OCCUPY o ON o.REQUEST_ID = r.REQUEST_ID
WHERE (r.BUSINESS_STATUS = 'CONFIRMED' AND o.STATUS <> 'CONFIRMED')
   OR (r.BUSINESS_STATUS = 'CANCELLED' AND o.STATUS <> 'CANCELLED')
   OR (r.BUSINESS_STATUS = 'EXPIRED' AND o.STATUS <> 'EXPIRED')
GROUP BY r.REQUEST_ID, r.BUSINESS_REQUEST_NO, r.BUSINESS_STATUS, o.STATUS
ORDER BY r.REQUEST_ID;

PROMPT === 9. 锁表当前热点检查 ===

SELECT LOCK_KEY, UPDATED_AT
FROM PR_LIMIT_LOCK
WHERE UPDATED_AT > SYSDATE - (1 / 24)
ORDER BY UPDATED_AT DESC;

PROMPT === 10. 手工锁验证示例 ===
PROMPT 在会话 A 执行：
PROMPT SELECT * FROM PR_LIMIT_LOCK WHERE LOCK_KEY = '<LOCK_KEY>' FOR UPDATE;
PROMPT 在会话 B 执行同一 SQL，应等待会话 A COMMIT 或 ROLLBACK。
